"""
Полноценный сборщик словаря Stork на ровно 1000 уникальных слов.
Объединяет базовые 500 слов, ранее подготовленные партии и новые проверенные слова
по всем 12 категориям (A1, A2, B1) с немецким примером, русским и английским переводом.
"""
import json
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

# Дополнительные 280+ проверенных слов для достижения ровно 1000
ADDITIONAL_WORDS = [
    # === ESSEN & GETRÄNKE (Еда и напитки) ===
    ("Karotte", "die", "die Karotten", "A1", "Essen", "Frische Karotten sind reich an Vitaminen.", "морковь", "Свежая морковь богата витаминами.", "carrot", "Fresh carrots are rich in vitamins."),
    ("Erbse", "die", "die Erbsen", "A2", "Essen", "Grüne Erbsen passen hervorragend zur Suppe.", "горох / горошек", "Зеленый горошек отлично подходит к супу.", "pea", "Green peas go wonderfully with soup."),
    ("Bohne", "die", "die Bohnen", "A2", "Essen", "Weiße Bohnen enthalten viel gesundes Eiweiß.", "фасоль / боб", "Белая фасоль содержит много полезного белка.", "bean", "White beans contain plenty of healthy protein."),
    ("Mais", "der", "die Maise", "A1", "Essen", "Süßer Mais schmeckt gegrillt besonders lecker.", "кукуруза", "Сладкая кукуруза на гриле особенно вкусная.", "corn / maize", "Sweet corn tastes especially delicious grilled."),
    ("Brokkoli", "der", "die Brokkoli", "A1", "Essen", "Gedämpfter Brokkoli ist gesund und knackig.", "брокколи", "Приготовленный на пару брокколи полезен и хрустит.", "broccoli", "Steamed broccoli is healthy and crunchy."),
    ("Spinat", "der", "die Spinate", "A1", "Essen", "Frischer Spinat schmeckt im Salat und in der Pasta.", "шпинат", "Свежий шпинат вкусен в салате и в пасте.", "spinach", "Fresh spinach tastes good in salad and pasta."),
    ("Petersilie", "die", "die Petersilien", "A2", "Essen", "Ich streue frische Petersilie über die Kartoffeln.", "петрушка", "Я посыпаю свежей петрушкой картофель.", "parsley", "I sprinkle fresh parsley over the potatoes."),
    ("Zimt", "der", "die Zimte", "A2", "Essen", "Zimt duftet herrlich im winterlichen Gebäck.", "корица", "Корица чудесно пахнет в зимней выпечке.", "cinnamon", "Cinnamon smells wonderful in winter pastries."),
    ("Vanille", "die", "die Vanillen", "A2", "Essen", "Eis mit echter Vanille schmeckt unübertroffen.", "ваниль", "Мороженое с настоящей ванилью бесподобно на вкус.", "vanilla", "Ice cream with real vanilla tastes unsurpassed."),
    ("Pflaume", "die", "die Pflaumen", "A2", "Essen", "Im Herbst backen wir Kuchen mit blauen Pflaumen.", "слива", "Осенью мы печем пирог с синими сливами.", "plum", "In autumn we bake cake with blue plums."),
    ("Himbeere", "die", "die Himbeeren", "A2", "Essen", "Süße Himbeeren wachsen an Sträuchern im Garten.", "малина", "Сладкая малина растет на кустах в саду.", "raspberry", "Sweet raspberries grow on bushes in the garden."),
    ("Heidelbeere", "die", "die Heidelbeeren", "A2", "Essen", "Frische Heidelbeeren färben die Zunge blau.", "черника / голубика", "Свежая черника красит язык в синий цвет.", "blueberry", "Fresh blueberries turn your tongue blue."),
    ("Walnuss", "die", "die Walnüsse", "A2", "Essen", "Walnüsse sind gesund für das menschliche Gehirn.", "грецкий орех", "Грецкие орехи полезны для человеческого мозга.", "walnut", "Walnuts are healthy for the human brain."),
    ("Mandel", "die", "die Mandeln", "A2", "Essen", "Gebrannte Mandeln duften auf dem Weihnachtsmarkt.", "миндаль", "Жареный миндаль пахнет на рождественской ярмарке.", "almond", "Roasted almonds smell inviting at the Christmas market."),
    ("Olivenöl", "das", "die Olivenöle", "A1", "Essen", "Gutes Olivenöl gehört in jeden frischen Salat.", "оливковое масло", "Хорошее оливковое масло необходимо в каждом салате.", "olive oil", "Good olive oil belongs in every fresh salad."),
    ("Pfannkuchen", "der", "die Pfannkuchen", "A1", "Essen", "Am Sonntag backt Oma süße Pfannkuchen.", "блин / оладья", "В воскресенье бабушка печет сладкие блины.", "pancake", "On Sunday grandma bakes sweet pancakes."),
    ("Spiegelei", "das", "die Spiegeleier", "A1", "Essen", "Zum Frühstück esse ich zwei Spiegeleier mit Speck.", "яичница-глазунья", "На завтрак я ем яичницу-глазунью из двух яиц с беконом.", "fried egg", "For breakfast I eat two fried eggs with bacon."),
    ("Lachs", "der", "die Lachse", "A1", "Essen", "Frischer Lachs schmeckt gebraten hervorragend.", "лосось / семга", "Свежий жареный лосось великолепен на вкус.", "salmon", "Fresh salmon tastes superb when pan-fried."),
    ("Thunfisch", "der", "die Thunfische", "A2", "Essen", "Ein Salat mit Thunfisch ist leicht und gesund.", "тунец", "Салат с тунцом легкий и полезный.", "tuna", "A salad with tuna is light and healthy."),
    ("Garnele", "die", "die Garnelen", "A2", "Essen", "Gegrillte Garnelen mit Knoblauch sind eine Delikatesse.", "креветка", "Креветки на гриле с чесноком - это деликатес.", "shrimp / prawn", "Grilled prawns with garlic are a delicacy."),

    # === ZUHAUSE & MÖBEL (Дом и быт) ===
    ("Nachttisch", "der", "die Nachttische", "A1", "Zuhause", "Auf dem Nachttisch steht eine kleine Lampe.", "прикроватная тумбочка", "На прикроватной тумбочке стоит маленькая лампа.", "nightstand / bedside table", "On the nightstand stands a small lamp."),
    ("Schreibtisch", "der", "die Schreibtische", "A1", "Zuhause", "Mein Laptop steht auf dem großen Schreibtisch.", "письменный стол", "Мой ноутбук стоит на большом письменном столе.", "desk", "My laptop is on the large desk."),
    ("Esstisch", "der", "die Esstische", "A1", "Zuhause", "Die ganze Familie versammelt sich am Esstisch.", "обеденный стол", "Вся семья собирается за обеденным столом.", "dining table", "The whole family gathers at the dining table."),
    ("Couchtisch", "der", "die Couchtische", "A2", "Zuhause", "Zeitschriften und Tee stehen auf dem Couchtisch.", "журнальный столик", "Журналы и чай стоят на журнальном столике.", "coffee table", "Magazines and tea are on the coffee table."),
    ("Kommode", "die", "die Kommoden", "A2", "Zuhause", "In den Schubladen der Kommode liegen T-Shirts.", "комод", "В ящиках комода лежат футболки.", "chest of drawers / dresser", "In the dresser drawers lie t-shirts."),
    ("Bücherregal", "das", "die Bücherregale", "A1", "Zuhause", "Im Bücherregal stehen über hundert Romane.", "книжный шкаф / полка", "В книжном шкафу стоит более ста романов.", "bookshelf", "In the bookshelf stand over a hundred novels."),
    ("Garderobe", "die", "die Garderoben", "A1", "Zuhause", "Hänge deine Jacke bitte an die Garderobe.", "вешалка / прихожая", "Повесь свою куртку, пожалуйста, на вешалку.", "coat rack / wardrobe", "Please hang your jacket on the coat rack."),
    ("Schuhschrank", "der", "die Schuhschränke", "A2", "Zuhause", "Im Schuhschrank ist Platz für zwanzig Paar Schuhe.", "шкаф для обуви", "В обувном шкафу есть место для двадцати пар обуви.", "shoe rack / cabinet", "In the shoe cabinet there is room for twenty pairs of shoes."),
    ("Wanduhr", "die", "die Wanduhren", "A1", "Zuhause", "Die Wanduhr in der Küche tickt leise.", "настенные часы", "Настенные часы на кухне тихо тикают.", "wall clock", "The wall clock in the kitchen ticks quietly."),
    ("Wecker", "der", "die Wecker", "A1", "Zuhause", "Mein Wecker klingelt jeden Morgen um sieben Uhr.", "будильник", "Мой будильник звенит каждое утро в семь часов.", "alarm clock", "My alarm clock rings every morning at seven o'clock."),
    ("Stehlampe", "die", "die Stehlampen", "A2", "Zuhause", "Die Stehlampe neben dem Sessel spendet warmes Licht.", "торшер / напольная лампа", "Торшер рядом с креслом дает теплый свет.", "floor lamp", "The floor lamp next to the armchair provides warm light."),
    ("Bettdecke", "die", "die Bettdecken", "A1", "Zuhause", "Die dicke Bettdecke hält im Winter herrlich warm.", "одеяло", "Толстое одеяло чудесно согревает зимой.", "duvet / blanket", "The thick duvet keeps wonderfully warm in winter."),
    ("Bettwäsche", "die", "die Bettwäschen", "A2", "Zuhause", "Frische Bettwäsche riecht sauber nach Sommerwind.", "постельное белье", "Свежее постельное белье пахнет летней чистотой.", "bed linen / bedding", "Fresh bed linen smells clean of summer wind."),
    ("Matratze", "die", "die Matratzen", "A2", "Zuhause", "Auf dieser neuen Matratze schlafe ich tief und fest.", "матрас", "На этом новом матрасе я сплю глубоко и крепко.", "mattress", "On this new mattress I sleep deeply and soundly."),
    ("Zahnbürste", "die", "die Zahnbürsten", "A1", "Zuhause", "Jeder sollte seine Zahnbürste alle drei Monate wechseln.", "зубная щетка", "Каждый должен менять зубную щетку раз в три месяца.", "toothbrush", "Everyone should replace their toothbrush every three months."),
    ("Zahnpasta", "die", "die Zahnpasten", "A1", "Zuhause", "Die Zahnpasta schmeckt frisch nach Pfefferminze.", "зубная паста", "Зубная паста имеет свежий вкус перечной мяты.", "toothpaste", "The toothpaste tastes fresh of peppermint."),
    ("Haartrockner", "der", "die Haartrockner", "A2", "Zuhause", "Nach dem Duschen trockne ich die Haare mit dem Haartrockner.", "фен для волос", "После душа я сушу волосы феном.", "hairdryer", "After showering I dry my hair with the hairdryer."),
    ("Kamm", "der", "die Kämme", "A1", "Zuhause", "Er kämmt seine Haare mit einem hölzernen Kamm.", "гребень / расческа", "Он расчесывает волосы деревянным гребнем.", "comb", "He combs his hair with a wooden comb."),
    ("Bürste", "die", "die Bürsten", "A1", "Zuhause", "Mit einer weichen Bürste pflegt sie ihr langes Haar.", "щетка (для волос)", "Мягкой щеткой она ухаживает за своими длинными волосами.", "brush / hairbrush", "With a soft brush she cares for her long hair."),
    ("Wäschekorb", "der", "die Wäschekörbe", "A2", "Zuhause", "Schmutzige Kleidung gehört in den Wäschekorb.", "корзина для белья", "Грязная одежда складывается в корзину для белья.", "laundry basket", "Dirty clothes belong in the laundry basket."),
    ("Mülleimer", "der", "die Mülleimer", "A1", "Zuhause", "Werfen Sie das Papier bitte in den Mülleimer.", "мусорное ведро", "Выбросьте бумагу, пожалуйста, в мусорное ведро.", "trash can / bin", "Please throw the paper into the trash can."),
    ("Kochtopf", "der", "die Kochtöpfe", "A1", "Zuhause", "Die Suppe kocht im großen Kochtopf auf dem Herd.", "кастрюля", "Суп варится в большой кастрюле на плите.", "cooking pot", "The soup boils in the large pot on the stove."),
    ("Bratpfanne", "die", "die Bratpfannen", "A2", "Zuhause", "In der Bratpfanne braten wir Kartoffeln goldbraun.", "сковорода для жарки", "На сковороде мы жарим картофель до золотистой корочки.", "frying pan / skillet", "In the frying pan we fry potatoes until golden brown."),
    ("Schneidebrett", "das", "die Schneidebretter", "A2", "Zuhause", "Auf dem hölzernen Schneidebrett schneide ich Zwiebeln.", "разделочная доска", "На деревянной разделочной доске я режу лук.", "cutting board", "On the wooden cutting board I chop onions."),

    # === STADT & VERKEHR (Город и инфраструктура) ===
    ("Marktplatz", "der", "die Marktplätze", "A1", "Stadt", "Der historische Marktplatz ist voller Cafés.", "рыночная площадь", "Историческая рыночная площадь полна кафе.", "market square", "The historic market square is full of cafes."),
    ("Fußgängerzone", "die", "die Fußgängerzonen", "A2", "Stadt", "In der Fußgängerzone dürfen keine Autos fahren.", "пешеходная зона", "В пешеходной зоне машинам ездить запрещено.", "pedestrian zone", "In the pedestrian zone cars are not allowed to drive."),
    ("Hauptbahnhof", "der", "die Hauptbahnhöfe", "A1", "Stadt", "Vom Hauptbahnhof fahren Züge in alle Richtungen.", "главный вокзал", "С главного вокзала поезда отправляются во все направления.", "central train station", "From the central station trains depart in all directions."),
    ("Bushaltestelle", "die", "die Bushaltestellen", "A1", "Stadt", "Die Leute warten an der Bushaltestelle im Regen.", "автобусная остановка", "Люди ждут на автобусной остановке под дождем.", "bus stop", "People are waiting at the bus stop in the rain."),
    ("Gehweg", "der", "die Gehwege", "A1", "Stadt", "Kinder fahren mit dem Roller auf dem sicheren Gehweg.", "тротуар / пешеходная дорожка", "Дети катаются на самокате по безопасному тротуару.", "sidewalk / footway", "Children ride scooters on the safe sidewalk."),
    ("Zebrastreifen", "der", "die Zebrastreifen", "A1", "Stadt", "Autos müssen vor dem Zebrastreifen anhalten.", "пешеходный переход («зебра»)", "Автомобили обязаны останавливаться перед «зеброй».", "crosswalk / zebra crossing", "Cars must stop before the zebra crossing."),
    ("Parkbank", "die", "die Parkbänke", "A1", "Stadt", "Auf der Parkbank sitzt ein Mann und liest Zeitung.", "скамейка в парке", "На скамейке в парке сидит мужчина и читает газету.", "park bench", "On the park bench a man is sitting and reading a newspaper."),
    ("Denkmal", "das", "die Denkmäler", "A2", "Stadt", "Das Denkmal erinnert an berühmte Dichter der Stadt.", "памятник / монумент", "Памятник напоминает об известных поэтах города.", "monument / memorial", "The monument commemorates famous poets of the city."),
    ("Altstadt", "die", "die Altstädte", "A1", "Stadt", "In der Altstadt gibt es viele kleine Gassen.", "старый город (исторический центр)", "В старом городе много маленьких переулков.", "old town / historic center", "In the old town there are many small alleys."),
    ("Vorort", "der", "die Vororte", "A2", "Stadt", "Viele Familien wohnen lieber im ruhigen Vorort.", "пригород", "Многие семьи предпочитают жить в тихом пригороде.", "suburb", "Many families prefer living in a quiet suburb."),
    ("Stadtviertel", "das", "die Stadtviertel", "A2", "Stadt", "Unser Stadtviertel ist lebendig und grün.", "городской квартал / район", "Наш городской район оживленный и зеленый.", "neighborhood / city district", "Our city district is lively and green."),
    ("Baustelle", "die", "die Baustellen", "A2", "Stadt", "Wegen der Baustelle ist die Straße gesperrt.", "строительная площадка / стройка", "Из-за стройки улица перекрыта.", "construction site", "Due to the construction site the street is closed."),
    ("Kran", "der", "die Kräne", "A2", "Stadt", "Der hohe Kran hebt schwere Betonplatten.", "строительный кран", "Высокий кран поднимает тяжелые бетонные плиты.", "crane", "The tall crane lifts heavy concrete slabs."),
    ("Sackgasse", "die", "die Sackgassen", "A2", "Stadt", "Diese kleine Straße ist eine Sackgasse ohne Durchgang.", "тупик", "Эта маленькая улица является тупиком без сквозного проезда.", "dead end / cul-de-sac", "This small street is a cul-de-sac with no through road."),
    ("Einbahnstraße", "die", "die Einbahnstraßen", "A2", "Stadt", "Achten Sie auf das Schild: Das ist eine Einbahnstraße.", "улица с односторонним движением", "Обратите внимание на знак: это улица с односторонним движением.", "one-way street", "Pay attention to the sign: This is a one-way street."),
    ("Radweg", "der", "die Radwege", "A1", "Stadt", "Der breite Radweg führt direkt am Fluss entlang.", "велосипедная дорожка", "Широкая велодорожка идет прямо вдоль реки.", "bicycle path / bike lane", "The wide bike lane leads directly along the river."),
    ("Fahrradständer", "der", "die Fahrradständer", "A2", "Stadt", "Vor der Bibliothek gibt es sichere Fahrradständer.", "велопарковка / стойка для велосипедов", "Перед библиотекой есть надежные велопарковки.", "bike rack", "In front of the library there are secure bike racks."),
    ("Parkhaus", "das", "die Parkhäuser", "A1", "Stadt", "Wir stellen unser Auto im überdachten Parkhaus ab.", "многоуровневая парковка", "Мы ставим машину на крытую парковку.", "parking garage", "We park our car in the covered parking garage."),
    ("Tiefgarage", "die", "die Tiefgaragen", "A2", "Stadt", "Die Bewohner parken bequem in der Tiefgarage.", "подземный гараж / паркинг", "Жильцы удобно паркуются в подземном паркинге.", "underground parking", "The residents park conveniently in the underground parking lot."),
    ("Schranke", "die", "die Schranken", "A2", "Stadt", "Die Schranke öffnet sich automatisch nach Bezahlung.", "шлагбаум", "Шлагбаум открывается автоматически после оплаты.", "barrier / barrier gate", "The barrier opens automatically after payment."),

    # === MENSCHEN & FAMILIE (Люди и семья) ===
    ("Säugling", "der", "die Säuglinge", "A2", "Menschen", "Der Säugling schläft friedlich in der Wiege.", "младенец / грудной ребенок", "Младенец мирно спит в колыбели.", "infant / baby", "The infant sleeps peacefully in the cradle."),
    ("Kleinkind", "das", "die Kleinkinder", "A1", "Menschen", "Das Kleinkind lernt gerade seine ersten Schritte.", "малыш (ясельного возраста)", "Малыш как раз учится делать первые шаги.", "toddler", "The toddler is just learning its first steps."),
    ("Teenager", "der", "die Teenager", "A1", "Menschen", "Viele Teenager hören Musik über Kopfhörer.", "подросток", "Многие подростки слушают музыку через наушники.", "teenager / teen", "Many teenagers listen to music through headphones."),
    ("Senior", "der", "die Senioren", "A2", "Menschen", "Die Senioren machen gern Spaziergänge im Park.", "пожилой человек / сеньор", "Пожилые люди любят гулять в парке.", "senior citizen", "Senior citizens enjoy taking walks in the park."),
    ("Rentner", "der", "die Rentner", "A2", "Menschen", "Als Rentner hat mein Großvater viel freie Zeit.", "пенсионер", "Будучи пенсионером, мой дедушка имеет много свободного времени.", "retiree / pensioner", "As a pensioner my grandfather has plenty of free time."),
    ("Passant", "der", "die Passanten", "A2", "Menschen", "Ein freundlicher Passant zeigte mir den Weg.", "прохожий", "Дружелюбный прохожий указал мне дорогу.", "passerby", "A friendly passerby showed me the way."),
    ("Fußgänger", "der", "die Fußgänger", "A1", "Menschen", "Fußgänger haben an der grünen Ampel Vorrang.", "пешеход", "Пешеходы имеют преимущество на зеленый свет светофора.", "pedestrian", "Pedestrians have priority at a green traffic light."),
    ("Bewohner", "der", "die Bewohner", "A2", "Menschen", "Die Bewohner des Hauses kennen sich alle gut.", "житель / жилец дома", "Жильцы дома все хорошо знают друг друга.", "resident / occupant", "The occupants of the house all know each other well."),
    ("Einwohner", "der", "die Einwohner", "A2", "Menschen", "Berlin hat rund drei Komma sieben Millionen Einwohner.", "житель (города/страны)", "В Берлине около 3,7 миллиона жителей.", "inhabitant / citizen", "Berlin has around 3.7 million inhabitants."),
    ("Urgroßvater", "der", "die Urgroßväter", "A2", "Menschen", "Mein Urgroßvater feiert seinen neunzigsten Geburtstag.", "прадедушка", "Мой прадедушка празднует свое 90-летие.", "great-grandfather", "My great-grandfather celebrates his ninetieth birthday."),
    ("Urgroßmutter", "die", "die Urgroßmütter", "A2", "Menschen", "Urgroßmutter erzählte uns spannende Geschichten.", "прабабушка", "Прабабушка рассказывала нам увлекательные истории.", "great-grandmother", "Great-grandmother told us thrilling stories."),
    ("Schwiegervater", "der", "die Schwiegerväter", "A2", "Menschen", "Mein Schwiegervater hilft uns bei der Renovierung.", "свекор / тесть", "Мой тесть помогает нам с ремонтом.", "father-in-law", "My father-in-law helps us with the renovation."),
    ("Schwiegermutter", "die", "die Schwiegermütter", "A2", "Menschen", "Meine Schwiegermutter kocht am Sonntag für alle.", "свекровь / теща", "Моя теща готовит в воскресенье для всех.", "mother-in-law", "My mother-in-law cooks on Sunday for everyone."),
    ("Schwiegersohn", "der", "die Schwiegersöhne", "A2", "Menschen", "Ihr neuer Schwiegersohn ist ein sehr höflicher Mann.", "зять (муж дочери)", "Их новый зять - очень вежливый мужчина.", "son-in-law", "Their new son-in-law is a very polite man."),
    ("Schwiegertochter", "die", "die Schwiegertöchter", "A2", "Menschen", "Die Schwiegertochter brachte Blumen zum Besuch mit.", "невестка / сноха", "Невестка принесла цветы к визиту.", "daughter-in-law", "The daughter-in-law brought flowers to the visit."),
    ("Schwager", "der", "die Schwäger", "A2", "Menschen", "Mein Schwager spielt jedes Wochenende Tennis mit mir.", "деверь / шурин / зять (брат супруга)", "Мой шурин каждые выходные играет со мной в теннис.", "brother-in-law", "My brother-in-law plays tennis with me every weekend."),
    ("Schwägerin", "die", "die Schwägerinnen", "A2", "Menschen", "Meine Schwägerin arbeitet als Ärztin in München.", "золовка / свояченица", "Моя свояченица работает врачом в Мюнхене.", "sister-in-law", "My sister-in-law works as a doctor in Munich."),
    ("Neffe", "der", "die Neffen", "A2", "Menschen", "Mein kleiner Neffe liebt bunte Bilderbücher.", "племянник", "Мой маленький племянник обожает красочные книги с картинками.", "nephew", "My little nephew loves colorful picture books."),
    ("Nichte", "die", "die Nichten", "A2", "Menschen", "Meine Nichte geht seit diesem Jahr zur Schule.", "племянница", "Моя племянница с этого года ходит в школу.", "niece", "My niece has been going to school since this year."),
    ("Enkelkind", "das", "die Enkelkinder", "A1", "Menschen", "Opa spielt im Garten mit seinem Enkelkind.", "внук / внучка", "Дедушка играет в саду со своим внуком.", "grandchild", "Grandpa plays in the garden with his grandchild."),
    ("Enkelsohn", "der", "die Enkelsöhne", "A2", "Menschen", "Ihr Enkelsohn studiert Informatik in Berlin.", "внук", "Их внук изучает информатику в Берлине.", "grandson", "Their grandson studies computer science in Berlin."),
    ("Enkeltochter", "die", "die Enkeltöchter", "A2", "Menschen", "Die stolze Großmutter umarmt ihre Enkeltochter.", "внучка", "Гордая бабушка обнимает свою внучку.", "granddaughter", "The proud grandmother hugs her granddaughter."),
    ("Braut", "die", "die Bräute", "A2", "Menschen", "Die Braut trug ein wunderschönes weißes Kleid.", "невеста", "Невеста была одета в прекрасное белое платье.", "bride", "The bride wore a gorgeous white dress."),
    ("Bräutigam", "der", "die Bräutigame", "A2", "Menschen", "Der Bräutigam wartet aufgeregt vor dem Altar.", "жених", "Жених взволнованно ждет перед алтарем.", "groom / bridegroom", "The groom waits excitedly in front of the altar."),
    ("Ehepaar", "das", "die Ehepaare", "A2", "Menschen", "Das glückliche Ehepaar feiert goldene Hochzeit.", "супружеская пара", "Счастливая супружеская пара празднует золотую свадьбу.", "married couple", "The happy married couple celebrates their golden wedding."),

    # === ARBEIT & BERUF (Работа и профессии) ===
    ("Angestellte", "die", "die Angestellten", "A2", "Arbeit", "Viele Angestellte arbeiten heute im Homeoffice.", "служащая / сотрудница", "Многие служащие сегодня работают на удаленке.", "employee (female)", "Many female employees work from home today."),
    ("Mitarbeiter", "der", "die Mitarbeiter", "A2", "Arbeit", "Das Unternehmen beschäftigt über fünfhundert Mitarbeiter.", "сотрудник / работник", "Предприятие дает работу более чем пятистам сотрудникам.", "employee / coworker", "The company employs over five hundred workers."),
    ("Kollegin", "die", "die Kolleginnen", "A1", "Arbeit", "Meine neue Kollegin ist sehr hilfsbereit.", "коллега (женщина)", "Моя новая коллега очень отзывчивая.", "colleague (female)", "My new female colleague is very helpful."),
    ("Teamleiter", "der", "die Teamleiter", "A2", "Arbeit", "Unser Teamleiter leitet die wöchentliche Besprechung.", "руководитель команды / тимлид", "Наш тимлид руководит еженедельной планеркой.", "team lead", "Our team lead runs the weekly meeting."),
    ("Geschäftsführer", "der", "die Geschäftsführer", "B1", "Arbeit", "Der Geschäftsführer unterschrieb den wichtigen Vertrag.", "генеральный директор / управляющий", "Управляющий директор подписал важный контракт.", "managing director / CEO", "The managing director signed the important contract."),
    ("Praktikantin", "die", "die Praktikantinnen", "A2", "Arbeit", "Die junge Praktikantin lernt die Arbeitsabläufe kennen.", "практикантка", "Молодая практикантка знакомится с рабочими процессами.", "intern (female)", "The young female intern gets to know the workflows."),
    ("Mechaniker", "der", "die Mechaniker", "A2", "Arbeit", "Der Mechaniker repariert die Bremsen am Auto.", "механик / автослесарь", "Механик чинит тормоза на машине.", "mechanic", "The mechanic repairs the brakes on the car."),
    ("Elektriker", "der", "die Elektriker", "A2", "Arbeit", "Der Elektriker verlegt neue Stromkabel im Haus.", "электрик", "Электрик прокладывает новые силовые кабели в доме.", "electrician", "The electrician runs new power cables in the house."),
    ("Tischler", "der", "die Tischler", "A2", "Arbeit", "Der geschickte Tischler fertigt Möbel aus Massivholz.", "столяр / плотник", "Умелый столяр изготавливает мебель из массива дерева.", "carpenter / joiner", "The skilled carpenter crafts furniture from solid wood."),
    ("Maler", "der", "die Maler", "A1", "Arbeit", "Der Maler streicht die Wände in hellem Gelb.", "маляр / художник", "Маляр красит стены в светло-желтый цвет.", "painter", "The painter paints the walls in light yellow."),
    ("Bäcker", "der", "die Bäcker", "A1", "Arbeit", "Der Bäcker steht schon um vier Uhr morgens auf.", "пекарь", "Пекарь встает уже в четыре часа утра.", "baker", "The baker gets up at four o'clock in the morning."),
    ("Metzger", "der", "die Metzger", "A2", "Arbeit", "Beim Metzger kaufen wir frische Bratwurst.", "мясник", "У мясника мы покупаем свежие колбаски для жарки.", "butcher", "At the butcher we buy fresh bratwurst."),
    ("Friseur", "der", "die Friseure", "A1", "Arbeit", "Morgen habe ich einen Termin beim Friseur.", "парикмахер", "Завтра у меня запись к парикмахеру.", "hairdresser / barber", "Tomorrow I have an appointment at the hairdresser."),
    ("Gärtner", "der", "die Gärtner", "A1", "Arbeit", "Der Gärtner pflanzt bunte Tulpen im Beet.", "садовник", "Садовник сажает разноцветные тюльпаны на клумбе.", "gardener", "The gardener plants colorful tulips in the flowerbed."),
    ("Pilot", "der", "die Piloten", "A1", "Arbeit", "Der erfahrene Pilot fliegt die große Maschine sicher.", "пилот / летчик", "Опытный пилот уверенно ведет большой самолет.", "pilot", "The experienced pilot flies the big airliner safely."),
    ("Flugbegleiter", "der", "die Flugbegleiter", "A2", "Arbeit", "Der Flugbegleiter serviert Getränke an Bord.", "бортпроводник / стюард", "Бортпроводник разносит напитки на борту.", "flight attendant", "The flight attendant serves drinks on board."),
    ("Busfahrer", "der", "die Busfahrer", "A1", "Arbeit", "Der freundliche Busfahrer wartet auf die Schüler.", "водитель автобуса", "Приветливый водитель автобуса ждет школьников.", "bus driver", "The friendly bus driver waits for the students."),
    ("Postbote", "der", "die Postboten", "A1", "Arbeit", "Der Postbote wirft Briefe in den Kasten.", "почтальон", "Почтальон опускает письма в почтовый ящик.", "mail carrier / postman", "The mail carrier drops letters into the box."),

    # === NATUR & TIERE (Природа и животные) ===
    ("Gebirge", "das", "die Gebirge", "A2", "Natur", "Die Alpen sind das höchste Gebirge Mitteleuropas.", "горы / горная цепь", "Альпы - самые высокие горы в Центральной Европе.", "mountains / mountain range", "The Alps are the highest mountain range in Central Europe."),
    ("Hügel", "der", "die Hügel", "A2", "Natur", "Vom sanften Hügel blickt man weit über das Tal.", "холм", "С пологого холма открывается вид далеко на долину.", "hill", "From the gentle hill you look far over the valley."),
    ("Tal", "das", "die Täler", "A2", "Natur", "Im grünen Tal fließt ein klarer Bach.", "долина", "В зеленой долине течет прозрачный ручей.", "valley", "In the green valley flows a clear stream."),
    ("Höhle", "die", "die Höhlen", "A2", "Natur", "Bären schlafen im kalten Winter in einer Höhle.", "пещера", "Медведи спят холодной зимой в пещере.", "cave", "Bears sleep in a cave during the cold winter."),
    ("Fels", "der", "die Felsen", "A2", "Natur", "Kletterer sichern sich am steilen Fels ab.", "скала / утес", "Альпинисты страхуются на крутой скале.", "rock / cliff", "Climbers secure themselves on the steep rock."),
    ("Küste", "die", "die Küsten", "A2", "Natur", "An der deutschen Küste weht oft eine frische Brise.", "побережье", "На немецком побережье часто дует свежий бриз.", "coast / shoreline", "A fresh breeze often blows on the German coast."),
    ("Düne", "die", "die Dünen", "A2", "Natur", "Der Wind formt hohe Dünen aus feinem Sand.", "дюна", "Ветер образует высокие дюны из мелкого песка.", "dune / sand dune", "The wind shapes high dunes from fine sand."),
    ("Wüste", "die", "die Wüsten", "A2", "Natur", "In der heißen Wüste regnet es fast nie.", "пустыня", "В жаркой пустыне почти никогда не идет дождь.", "desert", "In the hot desert it hardly ever rains."),
    ("Dschungel", "der", "die Dschungel", "A2", "Natur", "Im dichten Dschungel leben viele exotische Vögel.", "джунгли", "В густых джунглях живет много экзотических птиц.", "jungle", "Many exotic birds live in the dense jungle."),
    ("Wiese", "die", "die Wiesen", "A1", "Natur", "Bunte Blumen blühen im Sommer auf der Wiese.", "луг / поляна", "Разноцветные цветы цветут летом на лугу.", "meadow", "Colorful flowers bloom on the meadow in summer."),
    ("Teich", "der", "die Teiche", "A1", "Natur", "Kleine Fische und Enten schwimmen im Teich.", "пруд", "Маленькие рыбки и утки плавают в пруду.", "pond", "Small fish and ducks swim in the pond."),
    ("Bach", "der", "die Bäche", "A2", "Natur", "Das kalte Wasser im Gebirgsbach ist glasklar.", "ручей", "Холодная вода в горном ручье кристально чистая.", "stream / brook", "The cold water in the mountain stream is crystal clear."),
    ("Quelle", "die", "die Quellen", "A2", "Natur", "An der natürlichen Quelle trinken wir frisches Wasser.", "источник / родник", "У природного родника мы пьем свежую воду.", "spring / source", "At the natural spring we drink fresh water."),
    ("Wasserfall", "der", "die Wasserfälle", "A2", "Natur", "Der laute Wasserfall stürzt ins tiefe Tal.", "водопад", "Шумный водопад срывается в глубокую долину.", "waterfall", "The loud waterfall plunges into the deep valley."),
    ("Ufer", "das", "die Ufer", "A2", "Natur", "Wir spazieren am sonnigen Ufer des Rheins entlang.", "берег (реки/озера)", "Мы гуляем вдоль солнечного берега Рейна.", "bank / shore", "We stroll along the sunny bank of the Rhine."),
    ("Bucht", "die", "die Buchten", "A2", "Natur", "Kleine Fischerboote liegen geschützt in der Bucht.", "бухта / залив", "Маленькие рыбацкие лодки укрылись в бухте.", "bay / cove", "Small fishing boats lie sheltered in the bay."),
    ("Ozean", "der", "die Ozeane", "A2", "Natur", "Der Atlantische Ozean trennt Europa von Amerika.", "океан", "Атлантический океан разделяет Европу и Америку.", "ocean", "The Atlantic Ocean separates Europe from America."),
    ("Gletscher", "der", "die Gletscher", "B1", "Natur", "Der alte Gletscher schmilzt im warmen Sommer.", "ледник", "Древний ледник тает жарким летом.", "glacier", "The ancient glacier melts in the warm summer."),
    ("Gewitter", "das", "die Gewitter", "A1", "Natur", "Bei einem heftigen Gewitter zucken Blitze am Himmel.", "гроза", "Во время сильной грозы в небе сверкают молнии.", "thunderstorm", "During a heavy thunderstorm lightning flashes in the sky."),
    ("Nebel", "der", "die Nebel", "A1", "Natur", "Dichter Nebel verhüllt morgens die Landschaft.", "туман", "Густой туман окутывает пейзаж по утрам.", "fog / mist", "Dense fog veils the landscape in the morning."),
    ("Regenbogen", "der", "die Regenbogen", "A1", "Natur", "Nach dem Schauer leuchtet ein bunter Regenbogen.", "радуга", "После ливня сияет разноцветная радуга.", "rainbow", "After the shower a colorful rainbow shines."),
    ("Schwan", "der", "die Schwäne", "A2", "Natur", "Ein weißer Schwan gleitet ruhig über den See.", "лебедь", "Белый лебедь спокойно скользит по озеру.", "swan", "A white swan glides calmly across the lake."),
    ("Taube", "die", "die Tauben", "A1", "Natur", "Auf dem Marktplatz picken viele Tauben Körner.", "голубь", "На рыночной площади многие голуби клюют зерна.", "pigeon / dove", "On the market square many pigeons peck grains."),
    ("Eule", "die", "die Eulen", "A2", "Natur", "Die kluge Eule jagt nachts im stillen Wald.", "сова", "Мудрая сова охотится ночью в тихом лесу.", "owl", "The wise owl hunts at night in the quiet forest."),
    ("Adler", "der", "die Adler", "A2", "Natur", "Der stolze Adler kreist hoch über den Gipfeln.", "орел", "Гордый орел кружит высоко над вершинами.", "eagle", "The proud eagle circles high above the peaks."),
    ("Hirsch", "der", "die Hirsche", "A2", "Natur", "Ein großer Hirsch steht majestätisch auf der Waldlichtung.", "олень", "Большой олень величественно стоит на лесной поляне.", "deer / stag", "A large deer stands majestically on the forest clearing."),
    ("Igel", "der", "die Igel", "A2", "Natur", "Der kleine Igel rollt sich bei Gefahr stachelig ein.", "ёж", "Маленький ёж сворачивается колючим клубком при опасности.", "hedgehog", "The little hedgehog curls up prickly when in danger."),
    ("Eichhörnchen", "das", "die Eichhörnchen", "A2", "Natur", "Das flinke Eichhörnchen sammelt Nüsse für den Winter.", "белка", "Проворная белка собирает орехи на зиму.", "squirrel", "The nimble squirrel collects nuts for the winter."),
    ("Frosch", "der", "die Frösche", "A2", "Natur", "Der grüne Frosch quakt laut am Rande des Teichs.", "лягушка", "Зеленая лягушка громко квакает на краю пруда.", "frog", "The green frog croaks loudly at the edge of the pond."),
    ("Schildkröte", "die", "die Schildkröten", "A2", "Natur", "Die alte Schildkröte bewegt sich gemächlich vorwärts.", "черепаха", "Старая черепаха неторопливо движется вперед.", "turtle / tortoise", "The old tortoise moves forward leisurely."),

    # === ZEIT & KALENDER (Время и календарь) ===
    ("Jahrhundert", "das", "die Jahrhunderte", "A2", "Zeit", "Wir leben heute im einundzwanzigsten Jahrhundert.", "столетие / век", "Мы живем сегодня в двадцать первом веке.", "century", "We live in the twenty-first century today."),
    ("Jahrzehnt", "das", "die Jahrzehnte", "B1", "Zeit", "In diesem Jahrzehnt hat sich die Technik stark verändert.", "десятилетие", "В этом десятилетии технологии сильно изменились.", "decade", "Technology has changed greatly in this decade."),
    ("Quartal", "das", "die Quartale", "B1", "Zeit", "Im vierten Quartal steigen die Umsätze deutlich an.", "квартал (три месяца)", "В четвертом квартале продажи заметно растут.", "quarter (financial)", "In the fourth quarter sales increase significantly."),
    ("Semester", "das", "die Semester", "A2", "Zeit", "Das neue Semester an der Uni beginnt im Oktober.", "семестр", "Новый семестр в университете начинается в октябре.", "semester", "The new semester at university begins in October."),
    ("Werktag", "der", "die Werktage", "A2", "Zeit", "Die Geschäfte haben an jedem Werktag geöffnet.", "будний / рабочий день", "Магазины открыты в каждый рабочий день.", "workday / weekday", "The shops are open on every weekday."),
    ("Ruhetag", "der", "die Ruhetage", "A2", "Zeit", "Montag ist im Museum ein fester Ruhetag.", "выходной день (в заведении)", "Понедельник в музее - постоянный выходной день.", "closing day / rest day", "Monday is a fixed closing day in the museum."),
    ("Urlaubstag", "der", "die Urlaubstage", "A2", "Zeit", "Er spart seine restlichen Urlaubstage für den Winter auf.", "день отпуска", "Он бережет оставшиеся дни отпуска на зиму.", "day of vacation / leave day", "He saves his remaining days of leave for the winter."),
    ("Jahrestag", "der", "die Jahrestage", "A2", "Zeit", "Sie feiern heute den fünften Jahrestag ihrer Hochzeit.", "годовщина", "Они празднуют сегодня пятую годовщину своей свадьбы.", "anniversary", "Today they celebrate their fifth wedding anniversary."),
    ("Jubiläum", "das", "die Jubiläen", "B1", "Zeit", "Das Unternehmen feiert sein hundertjähriges Jubiläum.", "юбилей", "Компания отмечает свой столетний юбилей.", "anniversary / jubilee", "The company celebrates its centennial jubilee."),
    ("Sonnenaufgang", "der", "die Sonnenaufgänge", "A2", "Zeit", "Wir standen früh auf, um den Sonnenaufgang zu sehen.", "восход солнца", "Мы встали рано, чтобы увидеть восход солнца.", "sunrise", "We got up early to watch the sunrise."),
    ("Sonnenuntergang", "der", "die Sonnenuntergänge", "A2", "Zeit", "Der rote Sonnenuntergang am Meer war atemberaubend.", "закат солнца", "Красный закат на море был захватывающим.", "sunset", "The red sunset at the sea was breathtaking."),
    ("Mittagszeit", "die", "die Mittagszeiten", "A1", "Zeit", "Zur Mittagszeit essen die Kollegen in der Kantine.", "обеденное время", "В обеденное время коллеги едят в столовой.", "lunchtime / noon", "At lunchtime colleagues eat in the cafeteria."),
    ("Mittagspause", "die", "die Mittagspausen", "A1", "Zeit", "In der Mittagspause gehe ich kurz an die frische Luft.", "обеденный перерыв", "В обеденный перерыв я ненадолго выхожу на свежий воздух.", "lunch break", "During the lunch break I briefly get some fresh air."),
    ("Dämmerung", "die", "die Dämmerungen", "B1", "Zeit", "In der Dämmerung schalten die Autos ihre Scheinwerfer ein.", "сумерки", "В сумерках машины включают свои фары.", "twilight / dusk", "At twilight cars turn on their headlights."),
    ("Nachtruhe", "die", "die Nachtruhen", "A2", "Zeit", "In Deutschland beginnt die gesetzliche Nachtruhe um zweiundzwanzig Uhr.", "ночной покой / время тишины", "В Германии законный ночной покой начинается в 22:00.", "night rest / quiet hours", "In Germany quiet hours legally begin at 10 pm."),
    ("Zeitspanne", "die", "die Zeitspannen", "B1", "Zeit", "In einer kurzen Zeitspanne lernte er fließend Deutsch.", "промежуток времени", "За короткий промежуток времени он научился бегло говорить по-немецки.", "timespan / period", "In a short period of time he learned fluent German."),
    ("Zeitraum", "der", "die Zeiträume", "B1", "Zeit", "Für diesen Zeitraum sind leider keine Zimmer frei.", "период времени", "На этот период времени, к сожалению, свободных номеров нет.", "period / timeframe", "Unfortunately no rooms are available for this timeframe."),
    ("Augenblick", "der", "die Augenblicke", "A2", "Zeit", "Warten Sie bitte einen kleinen Augenblick.", "мгновение / минутка", "Подождите, пожалуйста, одно мгновение.", "moment / instant", "Please wait for a brief moment."),
    ("Moment", "der", "die Momente", "A1", "Zeit", "Das war der schönste Moment unserer Reise.", "момент", "Это был самый прекрасный момент нашего путешествия.", "moment", "That was the most wonderful moment of our journey."),
    ("Weile", "die", "die Weilen", "A2", "Zeit", "Es dauerte eine Weile, bis der Bus kam.", "некоторое время / передышка", "Прошло некоторое время, прежде чем пришел автобус.", "while", "It took a while before the bus arrived."),
    ("Frist", "die", "die Fristen", "B1", "Zeit", "Die Frist für die Abgabe der Bewerbung endet morgen.", "срок / дедлайн", "Срок подачи заявления истекает завтра.", "deadline / period", "The deadline for submitting the application ends tomorrow."),

    # === LERNEN & WISSEN (Учеба и образование) ===
    ("Grundschule", "die", "die Grundschulen", "A1", "Lernen", "In Deutschland besuchen Kinder vier Jahre die Grundschule.", "начальная школа", "В Германии дети четыре года посещают начальную школу.", "elementary school / primary school", "In Germany children attend primary school for four years."),
    ("Gymnasium", "das", "die Gymnasien", "A2", "Lernen", "Nach dem Gymnasium machen die Schüler ihr Abitur.", "гимназия", "После гимназии ученики сдают экзамены на аттестат зрелости.", "grammar school / high school", "After high school students take their Abitur exams."),
    ("Berufsschule", "die", "die Berufsschulen", "A2", "Lernen", "Auszubildende lernen die Theorie in der Berufsschule.", "профтехучилище / колледж", "Стажеры изучают теорию в профессиональной школе.", "vocational school", "Trainees learn the theory in vocational school."),
    ("Hochschule", "die", "die Hochschulen", "A2", "Lernen", "Die technische Hochschule hat einen exzellenten Ruf.", "вуз / высшая школа", "Технический вуз имеет отличную репутацию.", "university / college", "The technical university has an excellent reputation."),
    ("Fakultät", "die", "die Fakultäten", "B1", "Lernen", "Er studiert an der juristischen Fakultät.", "факультет", "Он учится на юридическом факультете.", "faculty / department", "He studies at the law faculty."),
    ("Institut", "das", "die Institute", "A2", "Lernen", "Das wissenschaftliche Institut forscht an neuen Technologien.", "научный институт", "Научный институт исследует новые технологии.", "institute", "The scientific institute researches new technologies."),
    ("Hörsaal", "der", "die Hörsäle", "A2", "Lernen", "Der große Hörsaal ist mit hunderten Studenten gefüllt.", "лекционная аудитория", "Большая аудитория заполнена сотнями студентов.", "lecture hall", "The large lecture hall is packed with hundreds of students."),
    ("Seminarraum", "der", "die Seminarräume", "A2", "Lernen", "Die Diskussion findet im kleinen Seminarraum statt.", "семинарская аудитория", "Дискуссия проходит в небольшой семинарской комнате.", "seminar room", "The discussion takes place in the small seminar room."),
    ("Labor", "das", "die Labore", "A2", "Lernen", "Im chemischen Labor tragen alle weiße Kittel.", "лаборатория", "В химической лаборатории все носят белые халаты.", "laboratory / lab", "In the chemical lab everyone wears white coats."),
    ("Campus", "der", "die Campusse", "A2", "Lernen", "Der grüne Campus lädt im Sommer zum Lernen im Freien ein.", "университетский городок / кампус", "Зеленый кампус летом так и манит учиться на свежем воздухе.", "campus", "The green campus invites studying outdoors in summer."),
    ("Stundenplan", "der", "die Stundenpläne", "A1", "Lernen", "Der neue Stundenplan hängt an der Pinnwand.", "расписание уроков", "Новое расписание висит на доске объявлений.", "class schedule / timetable", "The new class timetable is pinned to the board."),
    ("Lehrplan", "der", "die Lehrpläne", "A2", "Lernen", "Der Lehrplan für Deutsch umfasst viele Themen.", "учебный план / программа", "Учебный план по немецкому языку охватывает много тем.", "curriculum / syllabus", "The German syllabus covers many topics."),
    ("Klausur", "die", "die Klausuren", "A2", "Lernen", "Morgen schreiben wir eine schwere Klausur in Mathematik.", "письменная контрольная / экзамен", "Завтра мы пишем сложную контрольную по математике.", "written exam / test", "Tomorrow we write a difficult written exam in mathematics."),
    ("Abschlussprüfung", "die", "die Abschlussprüfungen", "B1", "Lernen", "Nach der Abschlussprüfung feiern alle Absolventen.", "выпускной экзамен", "После выпускного экзамена все выпускники празднуют.", "final examination", "After the final exam all graduates celebrate."),
    ("Masterarbeit", "die", "die Masterarbeiten", "B1", "Lernen", "Sie schreibt ihre Masterarbeit über künstliche Intelligenz.", "магистерская диссертация", "Она пишет магистерскую работу об искусственном интеллекте.", "master's thesis", "She is writing her master's thesis on artificial intelligence."),
    ("Bachelorarbeit", "die", "die Bachelorarbeiten", "B1", "Lernen", "Er hat seine Bachelorarbeit pünktlich eingereicht.", "бакалаврская работа", "Он сдал свою бакалаврскую работу вовремя.", "bachelor's thesis", "He submitted his bachelor's thesis on time."),
    ("Zeugnis", "das", "die Zeugnisse", "A2", "Lernen", "Am Ende des Schuljahres bekommen die Kinder ihr Zeugnis.", "аттестат / табель с оценками", "В конце учебного года дети получают свой табель.", "report card / certificate", "At the end of the school year children receive their report cards."),
    ("Zertifikat", "das", "die Zertifikate", "A2", "Lernen", "Mit diesem Zertifikat beweist er sein Sprachniveau.", "сертификат", "Этим сертификатом он подтверждает свой языковой уровень.", "certificate", "With this certificate he proves his language level."),
    ("Federmäppchen", "das", "die Federmäppchen", "A1", "Lernen", "Im Federmäppchen liegen Stifte und Radiergummi.", "пенал для ручек", "В пенале лежат ручки и ластик.", "pencil case", "In the pencil case lie pens and an eraser."),
    ("Textmarker", "der", "die Textmarker", "A1", "Lernen", "Wichtige Sätze markiere ich mit dem gelben Textmarker.", "маркер / текстовыделитель", "Важные предложения я выделяю желтым текстовыделителем.", "highlighter", "Important sentences I highlight with the yellow highlighter."),
    ("Notizblock", "der", "die Notizblöcke", "A1", "Lernen", "Auf dem Notizblock schreibe ich mir Fragen auf.", "блокнот для заметок", "В блокноте для заметок я записываю свои вопросы.", "notepad / memo pad", "On the notepad I jot down questions for myself."),

    # === GESUNDHEIT & MEDIZIN (Здоровье и медицина) ===
    ("Hausarzt", "der", "die Hausärzte", "A1", "Gesundheit", "Bei Erkältung gehe ich zuerst zu meinem Hausarzt.", "терапевт / семейный врач", "При простуде я сначала иду к своему терапевту.", "family doctor / GP", "With a cold I first go to my family doctor."),
    ("Facharzt", "der", "die Fachärzte", "A2", "Gesundheit", "Für spezielle Untersuchungen brauche ich einen Facharzt.", "врач-специалист", "Для специальных обследований мне нужен профильный врач.", "specialist (medical)", "For specialized tests I need a medical specialist."),
    ("Kinderarzt", "der", "die Kinderärzte", "A1", "Gesundheit", "Der Kinderarzt untersucht das Baby liebevoll.", "детский врач / педиатр", "Педиатр заботливо осматривает малыша.", "pediatrician", "The pediatrician examines the baby lovingly."),
    ("Chirurg", "der", "die Chirurgen", "A2", "Gesundheit", "Der erfahrene Chirurg führte die Operation durch.", "хирург", "Опытный хирург провел операцию.", "surgeon", "The experienced surgeon performed the operation."),
    ("Psychologe", "der", "die Psychologen", "A2", "Gesundheit", "Ein guter Psychologe hört aufmerksam zu und hilft.", "психолог", "Хороший психолог внимательно слушает и помогает.", "psychologist", "A good psychologist listens attentively and helps."),
    ("Therapeut", "der", "die Therapeuten", "A2", "Gesundheit", "Der Therapeut zeigt Übungen für den kranken Rücken.", "терапевт / специалист по реабилитации", "Терапевт показывает упражнения для больной спины.", "therapist", "The therapist demonstrates exercises for the bad back."),
    ("Krankenschwester", "die", "die Krankenschwestern", "A1", "Gesundheit", "Die Krankenschwester bringt die Medizin ins Zimmer.", "медицинская сестра", "Медсестра приносит лекарство в палату.", "nurse (female)", "The nurse brings medicine into the room."),
    ("Krankenpfleger", "der", "die Krankenpfleger", "A2", "Gesundheit", "Der Krankenpfleger misst regelmäßig den Blutdruck.", "медбрат / санитар", "Медбрат регулярно измеряет артериальное давление.", "nurse / caregiver (male)", "The nurse regularly measures blood pressure."),
    ("Sanitäter", "der", "die Sanitäter", "A2", "Gesundheit", "Die Sanitäter leisteten sofort Erste Hilfe.", "санитар / фельдшер скорой помощи", "Фельдшеры скорой помощи оказали первую помощь.", "paramedic", "The paramedics provided first aid immediately."),
    ("Notarzt", "der", "die Notärzte", "A2", "Gesundheit", "Der Notarzt traf wenige Minuten nach dem Anruf ein.", "врач скорой помощи", "Врач неотложки прибыл через несколько минут после звонка.", "emergency physician", "The emergency doctor arrived a few minutes after the call."),
    ("Patient", "der", "die Patienten", "A1", "Gesundheit", "Der Arzt begrüßt den neuen Patienten im Behandlungszimmer.", "пациент", "Врач приветствует нового пациента в процедурном кабинете.", "patient (male)", "The doctor greets the new patient in the treatment room."),
    ("Patientin", "die", "die Patientinnen", "A1", "Gesundheit", "Die Patientin erholt sich schnell nach dem Eingriff.", "пациентка", "Пациентка быстро восстанавливается после процедуры.", "patient (female)", "The female patient recovers quickly after the procedure."),
    ("Wartezimmer", "das", "die Wartezimmer", "A1", "Gesundheit", "Im Wartezimmer liegen aktuelle Magazine aus.", "зал ожидания (в поликлинике)", "В приемной выложены свежие журналы.", "waiting room", "Current magazines are laid out in the waiting room."),
    ("Operationssaal", "der", "die Operationssäle", "B1", "Gesundheit", "Im Operationssaal herrschen höchste Hygienevorschriften.", "операционная", "В операционной действуют строжайшие правила гигиены.", "operating room", "Strict hygiene rules prevail in the operating room."),
    ("Intensivstation", "die", "die Intensivstationen", "B1", "Gesundheit", "Auf der Intensivstation werden schwere Fälle betreut.", "отделение реанимации", "В реанимации наблюдают за тяжелыми пациентами.", "intensive care unit (ICU)", "Severe cases are cared for in the intensive care unit."),
    ("Thermometer", "das", "die Thermometer", "A1", "Gesundheit", "Das Thermometer zeigt achtunddreißig Grad Fieber an.", "градусник / термометр", "Градусник показывает температуру 38 градусов.", "thermometer", "The thermometer shows thirty-eight degrees fever."),
    ("Verbandskasten", "der", "die Verbandskästen", "A2", "Gesundheit", "In jedem Auto muss ein vollständiger Verbandskasten sein.", "автомобильная аптечка", "В каждой машине должна быть полная аптечка первой помощи.", "first-aid kit", "A complete first-aid kit must be in every car."),
    ("Wundpflaster", "das", "die Wundpflaster", "A1", "Gesundheit", "Kleben Sie ein wasserdichtes Wundpflaster auf die Wunde.", "бактерицидный пластырь", "Наклейте водостойкий пластырь на рану.", "adhesive bandage", "Apply a waterproof adhesive bandage onto the wound."),
    ("Krücke", "die", "die Krücken", "A2", "Gesundheit", "Nach dem Beinbruch ging er wochenlang auf Krücken.", "костыль", "После перелома ноги он неделями ходил на костылях.", "crutch", "After breaking his leg he walked on crutches for weeks."),
    ("Rollstuhl", "der", "die Rollstühle", "A2", "Gesundheit", "Das Gebäude ist barrierefrei für Menschen im Rollstuhl.", "инвалидная коляска", "Здание доступно без барьеров для людей в инвалидных колясках.", "wheelchair", "The building is accessible for people in wheelchairs."),
    ("Impfung", "die", "die Impfungen", "A2", "Gesundheit", "Die Impfung schützt vor ansteckenden Krankheiten.", "прививка / вакцинация", "Вакцинация защищает от заразных заболеваний.", "vaccination / vaccine", "The vaccination protects against contagious diseases."),

    # === KLEIDUNG & MODE (Одежда) ===
    ("Winterjacke", "die", "die Winterjacken", "A1", "Kleidung", "Diese dicke Winterjacke hält auch bei Minusgraden warm.", "зимняя куртка", "Эта теплая зимняя куртка согревает даже в мороз.", "winter jacket", "This thick winter jacket keeps warm even in sub-zero temperatures."),
    ("Sommerkleid", "das", "die Sommerkleider", "A1", "Kleidung", "Sie trägt ein luftiges Sommerkleid mit Blumenmuster.", "летнее платье", "Она носит легкое летнее платье с цветочным узором.", "summer dress", "She wears an airy summer dress with a floral pattern."),
    ("Abendkleid", "das", "die Abendkleider", "A2", "Kleidung", "Für den Ball wählte sie ein elegantes Abendkleid.", "вечернее платье", "Для бала она выбрала элегантное вечернее платье.", "evening gown / dress", "For the ball she chose an elegant evening dress."),
    ("Lederjacke", "die", "die Lederjacken", "A2", "Kleidung", "Die schwarze Lederjacke sieht sehr modisch aus.", "кожаная куртка", "Черная кожаная куртка выглядит очень модно.", "leather jacket", "The black leather jacket looks very fashionable."),
    ("Regenjacke", "die", "die Regenjacken", "A1", "Kleidung", "Eine wasserdichte Regenjacke ist beim Wandern unverzichtbar.", "ветровка-дождевик", "Водонепроницаемая ветровка незаменима в походе.", "rain jacket", "A waterproof rain jacket is indispensable when hiking."),
    ("Strickjacke", "die", "die Strickjacken", "A2", "Kleidung", "An kühlen Abenden ziehe ich eine gemütliche Strickjacke über.", "кардиган / вязаная кофта", "Прохладными вечерами я накидываю уютный кардиган.", "cardigan / knit jacket", "On chilly evenings I put on a cozy cardigan."),
    ("Kapuzenpullover", "der", "die Kapuzenpullover", "A1", "Kleidung", "Er trägt am Wochenende gern einen bequemen Kapuzenpullover.", "худи / толстовка с капюшоном", "На выходных он любит носить удобную толстовку с капюшоном.", "hoodie", "On weekends he enjoys wearing a comfortable hoodie."),
    ("Polohemd", "das", "die Polohemden", "A2", "Kleidung", "Das blaue Polohemd eignet sich ideal fürs Büro.", "рубашка поло", "Синяя рубашка поло идеально подходит для офиса.", "polo shirt", "The blue polo shirt is ideal for the office."),
    ("Jogginghose", "die", "die Jogginghosen", "A1", "Kleidung", "Zu Hause zieht er als Erstes seine Jogginghose an.", "спортивные штаны", "Дома первым делом он надевает свои спортивные штаны.", "sweatpants / joggers", "At home he first puts on his sweatpants."),
    ("Bikini", "der", "die Bikinis", "A2", "Kleidung", "Für den Urlaub am Mittelmeer packt sie einen neuen Bikini ein.", "бикини", "В отпуск на Средиземное море она берет новый бикини.", "bikini", "For vacation by the Mediterranean she packs a new bikini."),
    ("Pyjama", "der", "die Pyjamas", "A2", "Kleidung", "Ein warmer Pyjama sorgt für gemütlichen Schlaf im Winter.", "пижама", "Теплая пижама обеспечивает уютный сон зимой.", "pajamas", "Warm pajamas ensure cozy sleep in winter."),
    ("Nachthemd", "das", "die Nachthemden", "A2", "Kleidung", "Das seidige Nachthemd fühlt sich angenehm leicht an.", "ночная рубашка", "Шелковая ночная рубашка приятно легкая на ощупь.", "nightgown", "The silky nightgown feels pleasantly light."),
    ("Morgenmantel", "der", "die Morgenmäntel", "A2", "Kleidung", "Beim ersten Kaffee am Morgen trage ich meinen Morgenmantel.", "халат (утренний)", "За первой чашкой кофе утром я надеваю домашний халат.", "dressing gown / morning robe", "During the first coffee in the morning I wear my dressing gown."),
    ("Unterhemd", "das", "die Unterhemden", "A2", "Kleidung", "Im tiefen Winter trage ich ein Unterhemd aus Wolle.", "майка / нижняя сорочка", "Глубокой зимой я ношу майку из шерсти.", "undershirt", "In deep winter I wear an undershirt made of wool."),
    ("Unterhose", "die", "die Unterhosen", "A2", "Kleidung", "Er packte frische Unterhosen in seine Reisetasche.", "трусы", "Он упаковал чистое белье в свою дорожную сумку.", "underpants / briefs", "He packed clean underpants into his travel bag."),
    ("Strumpfhose", "die", "die Strumpfhosen", "A2", "Kleidung", "Zum eleganten Rock passt eine schwarze Strumpfhose.", "колготки", "К элегантной юбке подходят черные колготки.", "tights / pantyhose", "Black tights match the elegant skirt well."),
    ("Wollsocken", "die", "die Wollsocken", "A1", "Kleidung", "Dicke Wollsocken halten die Füße vor dem Kamin warm.", "шерстяные носки", "Толстые шерстяные носки согревают ноги перед камином.", "wool socks", "Thick wool socks keep your feet warm in front of the fireplace."),

    # === REISE & VERKEHR (Путешествия) ===
    ("Flugticket", "das", "die Flugtickets", "A1", "Reise", "Ich habe das günstige Flugticket nach Rom ausgedruckt.", "авиабилет", "Я распечатал недорогой билет на самолет в Рим.", "flight ticket / plane ticket", "I printed the affordable flight ticket to Rome."),
    ("Bordkarte", "die", "die Bordkarten", "A1", "Reise", "Zeigen Sie Ihre Bordkarte bitte am Flugsteig vor.", "посадочный талон", "Пожалуйста, предъявите ваш посадочный талон у выхода на посадку.", "boarding pass", "Please show your boarding pass at the gate."),
    ("Gate", "das", "die Gates", "A1", "Reise", "Unser Flug boardet jetzt an Gate B zwölf.", "выход на посадку (гейт)", "Наш рейс садится сейчас у выхода В12.", "boarding gate", "Our flight is boarding now at gate B twelve."),
    ("Abflughalle", "die", "die Abflughallen", "A2", "Reise", "In der Abflughalle versammeln sich hunderte Passagiere.", "зал вылета", "В зале вылета собираются сотни пассажиров.", "departure hall", "In the departure hall hundreds of passengers gather."),
    ("Ankunftshalle", "die", "die Ankunftshallen", "A2", "Reise", "Er wartet mit einem Blumengruß in der Ankunftshalle.", "зал прилета", "Он ждет с цветами в зале прилета.", "arrivals hall", "He waits with flowers in the arrivals hall."),
    ("Gepäckband", "das", "die Gepäckbänder", "A2", "Reise", "Die Koffer kreisen langsam auf dem Gepäckband.", "багажная лента / транспортер", "Чемоданы медленно едут по багажной ленте.", "baggage carousel", "The suitcases slowly circle on the baggage carousel."),
    ("Handgepäck", "das", "die Handgepäcke", "A1", "Reise", "Nur ein kleines Handgepäck darf in die Kabine.", "ручная кладь", "Только одну небольшую ручную кладь можно взять в салон.", "carry-on luggage", "Only small carry-on luggage is allowed into the cabin."),
    ("Sicherheitskontrolle", "die", "die Sicherheitskontrollen", "A2", "Reise", "An der Sicherheitskontrolle muss man Flüssigkeiten vorzeigen.", "контроль безопасности (досмотр)", "На контроле безопасности необходимо предъявлять жидкости.", "security checkpoint", "At the security checkpoint you must present liquids."),
    ("Reisebüro", "das", "die Reisebüros", "A1", "Reise", "Im Reisebüro buchten wir einen All-Inclusive-Urlaub.", "туристическое агентство", "В турагентстве мы забронировали отдых по системе «все включено».", "travel agency", "At the travel agency we booked an all-inclusive vacation."),
    ("Reiseleiter", "der", "die Reiseleiter", "A2", "Reise", "Der kundige Reiseleiter erklärt die Geschichte der alten Burg.", "гид / экскурсовод", "Знающий гид объясняет историю старинного замка.", "tour guide", "The knowledgeable tour guide explains the history of the old castle."),
    ("Pauschalreise", "die", "die Pauschalreisen", "B1", "Reise", "Eine Pauschalreise beinhaltet Flug, Transfer und Hotel.", "пакетный тур / путевка", "Пакетный тур включает перелет, трансфер и отель.", "package tour / vacation package", "A package vacation includes flight, transfer and hotel."),
    ("Städtereise", "die", "die Städtereisen", "A2", "Reise", "Für das lange Wochenende planen wir eine Städtereise nach Wien.", "поездка по городам (сити-брейк)", "На длинные выходные мы планируем поездку в Вену.", "city trip / city break", "For the long weekend we are planning a city trip to Vienna."),
    ("Kreuzfahrtschiff", "das", "die Kreuzfahrtschiffe", "A2", "Reise", "Das riesige Kreuzfahrtschiff legt im Hafen von Hamburg an.", "круизный лайнер", "Огромный круизный лайнер швартуется в порту Гамбурга.", "cruise ship", "The huge cruise ship docks in the port of Hamburg."),
    ("Schnellzug", "der", "die Schnellzüge", "A2", "Reise", "Der moderne Schnellzug verbindet die beiden Metropolen in drei Stunden.", "скоростной поезд", "Современный скоростной поезд соединяет два мегаполиса за три часа.", "high-speed train", "The modern high-speed train connects both metropolises in three hours."),
    ("Schlafwagen", "der", "die Schlafwagen", "A2", "Reise", "Im Schlafwagen des Nachtzugs kann man bequem liegen.", "спальный вагон", "В спальном вагоне ночного поезда можно удобно лежать.", "sleeping car / sleeper", "In the sleeper car of the night train one can lie comfortably."),
    ("Speisewagen", "der", "die Speisewagen", "A2", "Reise", "Wir trinken einen heißen Kaffee im gemütlichen Speisewagen.", "вагон-ресторан", "Мы пьем горячий кофе в уютном вагоне-ресторане.", "dining car", "We drink hot coffee in the cozy dining car."),
    ("Tageskarte", "die", "die Tageskarten", "A1", "Reise", "Mit der Tageskarte können Sie den ganzen Tag Bus und Bahn nutzen.", "проездной на один день", "С дневным билетом вы можете весь день пользоваться автобусом и поездом.", "day ticket / day pass", "With the day pass you can use buses and trains all day."),
    ("Monatskarte", "die", "die Monatskarten", "A1", "Reise", "Die Monatskarte für die U-Bahn ist viel günstiger als Einzelfahrten.", "проездной на месяц", "Месячный проездной на метро намного выгоднее разовых поездок.", "monthly transit pass", "The monthly pass for the subway is much cheaper than single tickets."),
    ("Sitzplatzreservierung", "die", "die Sitzplatzreservierungen", "A2", "Reise", "Am Freitag empfiehlt sich im Zug eine feste Sitzplatzreservierung.", "бронирование места", "В пятницу в поезде рекомендуется оформлять бронь места.", "seat reservation", "On Friday a seat reservation is recommended on the train."),
    ("Taxistand", "der", "die Taxistände", "A1", "Reise", "Direkt vor dem Ausgang des Bahnhofs befindet sich ein Taxistand.", "стоянка такси", "Прямо перед выходом из вокзала находится стоянка такси.", "taxi stand / cab rank", "Directly in front of the station exit there is a taxi stand."),

    # === FREIZEIT & UNTERHALTUNG (Досуг и культура) ===
    ("Freizeitpark", "der", "die Freizeitparks", "A1", "Freizeit", "Die Achterbahn im großen Freizeitpark ist spektakulär.", "парк развлечений / аттракционов", "Американские горки в большом парке развлечений захватывают дух.", "amusement park / theme park", "The roller coaster in the large theme park is spectacular."),
    ("Zoo", "der", "die Zoos", "A1", "Freizeit", "Am Sonntag besuchen die Kinder die Tiere im Zoo.", "зоопарк", "В воскресенье дети навещают животных в зоопарке.", "zoo", "On Sunday the children visit the animals at the zoo."),
    ("Tierpark", "der", "die Tierparks", "A1", "Freizeit", "Im grünen Tierpark kann man Rehe aus der Hand füttern.", "парк дикой природы / зоопарк", "В зеленом парке животных можно кормить оленей с руки.", "wildlife park", "In the green wildlife park you can feed deer by hand."),
    ("Bowlingbahn", "die", "die Bowlingbahnen", "A2", "Freizeit", "Wir haben für Samstagabend eine Bowlingbahn reserviert.", "дорожка для боулинга", "Мы забронировали дорожку для боулинга на вечер субботы.", "bowling lane", "We reserved a bowling lane for Saturday evening."),
    ("Opernhaus", "das", "die Opernhäuser", "A2", "Freizeit", "Das historische Opernhaus bietet erstklassige Aufführungen.", "оперный театр", "Исторический оперный театр предлагает первоклассные постановки.", "opera house", "The historic opera house offers first-class performances."),
    ("Philharmonie", "die", "die Philharmonien", "B1", "Freizeit", "Das Orchester spielt berühmte Sinfonien in der Philharmonie.", "филармония", "Оркестр исполняет знаменитые симфонии в филармонии.", "philharmonic / concert hall", "The orchestra plays famous symphonies at the philharmonic."),
    ("Kunstausstellung", "die", "die Kunstausstellungen", "A2", "Freizeit", "Die neue Kunstausstellung zeigt zeitgenössische Skulpturen.", "художественная выставка", "Новая художественная выставка представляет современные скульптуры.", "art exhibition", "The new art exhibition presents contemporary sculptures."),
    ("Zirkus", "der", "die Zirkusse", "A1", "Freizeit", "Die Akrobaten und Clowns begeistern im Zirkus das Publikum.", "цирк", "Акробаты и клоуны восхищают публику в цирке.", "circus", "The acrobats and clowns delight the audience at the circus."),
    ("Jahrmarkt", "der", "die Jahrmärkte", "A2", "Freizeit", "Auf dem Jahrmarkt riecht es verlockend nach Zuckerwatte und Popcorn.", "ярмарка / базар с аттракционами", "На ярмарке заманчиво пахнет сахарной ватой и попкорном.", "fair / funfair", "At the funfair it smells enticingly of cotton candy and popcorn."),
    ("Weihnachtsmarkt", "der", "die Weihnachtsmärkte", "A1", "Freizeit", "Im Dezember trinken die Menschen heißen Glühwein auf dem Weihnachtsmarkt.", "рождественская ярмарка", "В декабре люди пьют горячий глинтвейн на рождественской ярмарке.", "Christmas market", "In December people drink hot mulled wine at the Christmas market."),
    ("Flohmarkt", "der", "die Flohmärkte", "A1", "Freizeit", "Auf dem Flohmarkt fand sie ein altes Buch aus dem 19. Jahrhundert.", "блошиный рынок", "На блошином рынке она нашла старинную книгу 19 века.", "flea market", "At the flea market she found an old book from the 19th century."),
    ("Tennisplatz", "der", "die Tennisplätze", "A2", "Freizeit", "Die rote Asche auf dem Tennisplatz wird regelmäßig gewässert.", "теннисный корт", "Красный грунт на корте регулярно поливают водой.", "tennis court", "The red clay on the tennis court is watered regularly."),
    ("Sporthalle", "die", "die Sporthallen", "A1", "Freizeit", "Im Winter trainiert die Handballmannschaft in der Sporthalle.", "спортивный зал", "Зимой гандбольная команда тренируется в спортзале.", "sports hall / gym", "In winter the handball team trains in the sports hall."),
    ("Schwimmbecken", "das", "die Schwimmbecken", "A2", "Freizeit", "Das große Schwimmbecken hat fünfzig Meter Länge.", "плавательный бассейн (чаша)", "Большая чаша бассейна имеет длину пятьдесят метров.", "swimming pool", "The large swimming pool is fifty meters long."),
    ("Hallenbad", "das", "die Hallenbäder", "A1", "Freizeit", "Wenn es draußen regnet, gehen wir ins warme Hallenbad.", "крытый плавательный бассейн", "Когда на улице идет дождь, мы идем в теплый крытый бассейн.", "indoor swimming pool", "When it rains outside, we go to the warm indoor pool."),
    ("Freibad", "das", "die Freibäder", "A1", "Freizeit", "Im heißen Hochsommer gibt es nichts Besseres als das Freibad.", "открытый бассейн", "Жарким летом нет ничего лучше открытого бассейна.", "outdoor pool / open-air bath", "In hot midsummer there is nothing better than the outdoor pool."),
    # === ДОПОЛНИТЕЛЬНЫЕ 42 СЛОВА ДО РОВНО 1000 ===
    ("Reisekoffer", "der", "die Reisekoffer", "A1", "Reise", "Der große Reisekoffer passt in den Kofferraum.", "чемодан для путешествий", "Большой чемодан помещается в багажник.", "travel suitcase", "The large suitcase fits into the trunk."),
    ("Auslandsreise", "die", "die Auslandsreisen", "A2", "Reise", "Für eine Auslandsreise benötigt man oft einen Reisepass.", "заграничная поездка", "Для заграничной поездки часто требуется загранпаспорт.", "trip abroad", "For a trip abroad you often need a passport."),
    ("Wanderkarte", "die", "die Wanderkarten", "A2", "Reise", "Mit der Wanderkarte finden wir den richtigen Pfad.", "туристическая карта", "С туристической картой мы находим правильную тропу.", "hiking map", "With the hiking map we find the right path."),
    ("Flugbegleiterin", "die", "die Flugbegleiterinnen", "A2", "Reise", "Die Flugbegleiterin erklärt die Sicherheitsregeln.", "стюардесса", "Стюардесса объясняет правила безопасности.", "flight attendant (female)", "The female flight attendant explains the safety rules."),
    ("Reisepass", "der", "die Reisepässe", "A1", "Reise", "Der Reisepass ist noch fünf Jahre gültig.", "заграничный паспорт", "Загранпаспорт действителен еще пять лет.", "passport", "The passport is valid for another five years."),
    ("Bordbistro", "das", "die Bordbistros", "A2", "Reise", "Im Bordbistro des Zugs gibt es warmen Tee und Brezeln.", "бистро в поезде", "В вагоне-бистро поезда есть горячий чай и крендели.", "train bistro", "In the train bistro there is hot tea and pretzels."),
    ("ICE", "der", "die ICEs", "A1", "Reise", "Der moderne ICE fährt mit dreihundert Stundenkilometern.", "скоростной поезд ICE", "Современный экспресс ICE идет со скоростью триста км/ч.", "ICE high-speed train", "The modern ICE train travels at three hundred km/h."),
    ("Abteil", "das", "die Abteile", "A2", "Reise", "In unserem Abteil im Zug reisen sechs Fahrgäste.", "купе (в поезде)", "В нашем купе в поезде едут шесть пассажиров.", "train compartment", "Six passengers are traveling in our train compartment."),
    ("Zwischenstopp", "der", "die Zwischenstopps", "A2", "Reise", "Wir machen einen kurzen Zwischenstopp in Frankfurt.", "пересадка / промежуточная остановка", "Мы делаем короткую промежуточную остановку во Франкфурте.", "stopover / layover", "We make a short layover in Frankfurt."),
    ("Campingplatz", "der", "die Campingplätze", "A2", "Reise", "Der Campingplatz liegt idyllisch direkt am See.", "кемпинг", "Кемпинг идиллически расположен прямо на берегу озера.", "campground / campsite", "The campsite is idyllically located right by the lake."),
    ("Jugendherberge", "die", "die Jugendherbergen", "A2", "Reise", "Schulklassen übernachten oft in einer Jugendherberge.", "молодежный хостел", "Школьные классы часто ночуют в хостеле.", "youth hostel", "School classes often stay overnight in a youth hostel."),
    ("Pension", "die", "die Pensionen", "A2", "Reise", "In den Bergen buchten wir ein gemütliches Zimmer in einer Pension.", "пансион / гостевой дом", "В горах мы забронировали уютную комнату в пансионе.", "guesthouse / pension", "In the mountains we booked a cozy room in a guesthouse."),
    ("Ferienwohnung", "die", "die Ferienwohnungen", "A2", "Reise", "Die Ferienwohnung an der Ostsee hat eine große Küche.", "квартира для отдыха / апартаменты", "В квартире для отдыха на Балтийском море большая кухня.", "holiday apartment", "The holiday apartment on the Baltic Sea has a large kitchen."),
    ("Bergpass", "der", "die Bergpässe", "B1", "Reise", "Der steile Bergpass ist im Winter wegen Schnee gesperrt.", "горный перевал", "Крутой горный перевал закрыт зимой из-за снега.", "mountain pass", "The steep mountain pass is closed in winter due to snow."),
    ("Wanderweg", "der", "die Wanderwege", "A1", "Reise", "Der markierte Wanderweg führt durch den schattigen Wald.", "туристическая пешеходная тропа", "Размеченная тропа ведет через тенистый лес.", "hiking trail", "The marked hiking trail leads through the shady forest."),
    ("Landkarte", "die", "die Landkarten", "A1", "Reise", "Auf der alten Landkarte suchen wir den kleinen Ort.", "географическая карта", "На старой карте мы ищем этот маленький поселок.", "geographical map", "On the old map we search for the small town."),
    ("Reisetasche", "die", "die Reisetaschen", "A1", "Reise", "Für den Wochenendtrip reicht eine praktische Reisetasche.", "дорожная сумка", "Для поездки на выходные достаточно практичной дорожной сумки.", "travel bag / duffel bag", "For the weekend trip a practical duffel bag is enough."),
    ("Flugdauer", "die", "die Flugdauern", "A2", "Reise", "Die reine Flugdauer nach Mallorca beträgt zwei Stunden.", "продолжительность полета", "Чистая длительность полета на Майорку составляет два часа.", "flight duration", "The pure flight duration to Mallorca is two hours."),
    ("Reisedokument", "das", "die Reisedokumente", "B1", "Reise", "Halten Sie alle Reisedokumente bei der Einreise bereit.", "проездной документ", "Держите все проездные документы наготове при въезде.", "travel document", "Keep all travel documents ready when entering the country."),

    ("Wochentag", "der", "die Wochentage", "A1", "Zeit", "Welcher Wochentag ist heute?", "день недели", "Какой сегодня день недели?", "day of the week", "Which day of the week is it today?"),
    ("Arbeitstag", "der", "die Arbeitstage", "A1", "Zeit", "Nach einem anstrengenden Arbeitstag koche ich gern.", "рабочий день", "После напряженного рабочего дня я люблю готовить.", "working day / workday", "After a stressful working day I enjoy cooking."),
    ("Schulferien", "die", "die Schulferien", "A1", "Zeit", "In den Schulferien fahren viele Familien ans Meer.", "школьные каникулы", "В школьные каникулы многие семьи едут на море.", "school holidays / vacation", "During the school holidays many families go to the sea."),
    ("Morgenstunde", "die", "die Morgenstunden", "A2", "Zeit", "Morgenstund hat Gold im Mund, sagt ein altes Sprichwort.", "утренний час", "Утренний час дарит успех, гласит старая пословица.", "morning hour", "The early bird catches the worm, says an old proverb."),
    ("Monatsende", "das", "die Monatsenden", "A2", "Zeit", "Am Monatsende bekommen die Angestellten ihr Gehalt.", "конец месяца", "В конце месяца служащие получают свою зарплату.", "end of the month", "At the end of the month employees receive their salary."),
    ("Jahreswechsel", "der", "die Jahreswechsel", "A2", "Zeit", "Zum Jahreswechsel gibt es um Mitternacht ein Feuerwerk.", "канун Нового года / смена года", "На стыке годов в полночь устраивают салют.", "turn of the year / New Year", "At the turn of the year there are fireworks at midnight."),
    ("Zeitzone", "die", "die Zeitzonen", "A2", "Zeit", "Zwischen Berlin und London liegt eine andere Zeitzone.", "часовой пояс", "Между Берлином и Лондоном лежит другой часовой пояс.", "time zone", "A different time zone lies between Berlin and London."),
    ("Zeitplan", "der", "die Zeitpläne", "A2", "Zeit", "Wir liegen genau im Zeitplan mit unserem Projekt.", "график / график по времени", "Мы идем точно по графику с нашим проектом.", "schedule / timetable", "We are right on schedule with our project."),

    ("Regenponcho", "der", "die Regenponchos", "A2", "Kleidung", "Bei plötzlichem Regen hilft ein leichter Regenponcho.", "дождевик-пончо", "При внезапном дожде выручает легкий дождевик-пончо.", "rain poncho", "In sudden rain a lightweight rain poncho helps."),
    ("Fliege", "die", "die Fliegen", "A2", "Kleidung", "Zum Frack trägt man eine weiße Fliege.", "галстук-бабочка", "К фраку надевают белую бабочку.", "bow tie", "With a tailcoat one wears a white bow tie."),
    ("Kopftuch", "das", "die Kopftücher", "A2", "Kleidung", "Sie band sich ein seidiges Kopftuch um das Haar.", "головной платок", "Она повязала шелковый платок на голову.", "headscarf", "She tied a silk headscarf around her hair."),
    ("Halstuch", "das", "die Halstücher", "A2", "Kleidung", "Ein buntes Halstuch schützt den Hals vor Wind.", "шейный платок", "Разноцветный шейный платок защищает шею от ветра.", "neckerchief / neck scarf", "A colorful neckerchief protects the neck from the wind."),
    ("Weste", "die", "die Westen", "A2", "Kleidung", "Er trägt eine warme Weste über dem Pullover.", "жилет / жилетка", "Он носит теплый жилет поверх свитера.", "vest / waistcoat", "He wears a warm vest over the sweater."),
    ("Strumpf", "der", "die Strümpfe", "A2", "Kleidung", "Sie kaufte feine Strümpfe für das neue Kleid.", "чулок", "Она купила тонкие чулки к новому платью.", "stocking", "She bought fine stockings for the new dress."),
    ("Daunenmantel", "der", "die Daunenmäntel", "A2", "Kleidung", "Der lange Daunenmantel schützt auch bei eisiger Kälte.", "пуховик / пуховое пальто", "Длинный пуховик защищает даже в ледяной мороз.", "down coat", "The long down coat protects even in freezing cold."),
    ("Schirmmütze", "die", "die Schirmmützen", "A2", "Kleidung", "Im Sommer schützt die Schirmmütze vor blendender Sonne.", "кепка / бейсболка", "Летом кепка с козырьком защищает от слепящего солнца.", "peaked cap / baseball cap", "In summer the peaked cap protects against dazzling sun."),

    ("Vokabelheft", "das", "die Vokabelhefte", "A1", "Lernen", "Im Vokabelheft notiere ich mir neue deutsche Wörter.", "тетрадь для слов / словарик", "В словарик я записываю новые немецкие слова.", "vocabulary notebook", "In the vocabulary notebook I write down new German words."),
    ("Fachbereich", "der", "die Fachbereiche", "B1", "Lernen", "Der Fachbereich Informatik bietet moderne Computerräume.", "факультет / отделение", "Факультет информатики предлагает современные компьютерные классы.", "department / faculty division", "The computer science department offers modern computer rooms."),
    ("Dozent", "der", "die Dozenten", "A2", "Lernen", "Der Dozent erklärt die grammatische Regel sehr verständlich.", "преподаватель вуза / доцент", "Преподаватель очень понятно объясняет грамматическое правило.", "lecturer / university instructor", "The lecturer explains the grammar rule very clearly."),
    ("Hausaufgabe", "die", "die Hausaufgaben", "A1", "Lernen", "Die Schüler machen fleißig ihre Hausaufgabe für morgen.", "домашнее задание", "Ученики старательно делают домашнее задание на завтра.", "homework", "The students diligently do their homework for tomorrow."),
    ("Notiz", "die", "die Notizen", "A1", "Lernen", "Ich mache mir eine kurze Notiz im Heft.", "заметка / запись", "Я делаю короткую заметку в тетради.", "note / memo", "I make a brief note in the notebook."),
    ("Klausurtermin", "der", "die Klausurtermine", "A2", "Lernen", "Der offizielle Klausurtermin ist der fünfzehnte Juli.", "дата экзамена / контрольной", "Официальная дата контрольной - пятнадцатое июля.", "exam date", "The official exam date is July fifteenth."),
    ("Schulhof", "der", "die Schulhöfe", "A1", "Lernen", "In der großen Pause spielen die Kinder auf dem Schulhof.", "школьный двор", "На большой перемене дети играют на школьном дворе.", "schoolyard / school playground", "During the long recess children play in the schoolyard."),
    ("Tischtennis", "das", "die Tischtennis", "A1", "Freizeit", "In den Pausen spielen wir Tischtennis auf dem Hof.", "настольный теннис", "На переменах мы играем в настольный теннис во дворе.", "table tennis / ping pong", "During breaks we play table tennis in the yard."),
    ("Waldrand", "der", "die Waldränder", "A2", "Natur", "Am Waldrand grasen morgens friedlich zwei Rehe.", "опушка леса", "На опушке леса утром мирно пасутся две косули.", "edge of the forest", "At the edge of the forest two deer graze peacefully in the morning.")
]

def build_catalog():
    # 1. Загружаем базовые 500 слов
    p500 = DATA_DIR / "words_500.json"
    with open(p500, "r", encoding="utf-8") as f:
        master_list = json.load(f)

    seen = {item["word"] for item in master_list}
    print(f"Base words loaded: {len(master_list)} (unique: {len(seen)})")

    # 2. Подгружаем партии из expand_to_1000 и generate_1000_words
    from scripts.expand_to_1000 import NEW_WORDS_BATCH
    from scripts.generate_1000_words import NEW_EXPANDED_WORDS

    combined_candidates = NEW_WORDS_BATCH + NEW_EXPANDED_WORDS + ADDITIONAL_WORDS

    added = 0
    for item in combined_candidates:
        w = item[0]
        if w not in seen:
            seen.add(w)
            master_list.append({
                "word": item[0],
                "article": item[1],
                "plural": item[2],
                "level": item[3],
                "category": item[4],
                "example_de": item[5],
                "translations": {
                    "ru": {"tr": item[6], "example_tr": item[7]},
                    "en": {"tr": item[8], "example_tr": item[9]}
                }
            })
            added += 1

    print(f"Candidates added: {added}. Current total: {len(master_list)}")
    
    cat_counts = Counter(w["category"] for w in master_list)
    lvl_counts = Counter(w["level"] for w in master_list)
    print("Categories distribution:", cat_counts)
    print("Levels distribution:", lvl_counts)

    # Сохраняем в words_1000.json
    out_file = DATA_DIR / "words_1000.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(master_list, f, ensure_ascii=False, indent=2)
    print(f"Successfully saved {len(master_list)} words to {out_file}!")

    return master_list

if __name__ == "__main__":
    catalog = build_catalog()
    assert len(catalog) == 1000, f"Expected 1000 words, got {len(catalog)}"
    print("VERIFICATION PASSED: Exactly 1000 words generated and validated!")
