"""
Генератор полного словаря Stork на 1000 уникальных слов.
Объединяет существующие 500 слов с 500 новыми словами по 12 темам.
"""
import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

NEW_EXPANDED_WORDS = [
    # --- REISE & VERKEHR (Путешествия) ---
    ("Flugzeug", "das", "die Flugzeuge", "A1", "Reise", "Das Flugzeug fliegt direkt nach Berlin.", "самолет", "Самолет летит прямо в Берлин.", "airplane", "The airplane flies directly to Berlin."),
    ("Flughafen", "der", "die Flughäfen", "A1", "Reise", "Wir müssen zwei Stunden früher am Flughafen sein.", "аэропорт", "Мы должны быть в аэропорту на два часа раньше.", "airport", "We have to be at the airport two hours earlier."),
    ("Flug", "der", "die Flüge", "A1", "Reise", "Unser Flug hatte eine halbe Stunde Verspätung.", "рейс / полет", "Наш рейс задержался на полчаса.", "flight", "Our flight was delayed by half an hour."),
    ("Ticket", "das", "die Tickets", "A1", "Reise", "Ich habe das Ticket online gebucht.", "билет", "Я забронировал билет онлайн.", "ticket", "I booked the ticket online."),
    ("Fahrkarte", "die", "die Fahrkarten", "A1", "Reise", "Haben Sie eine gültige Fahrkarte für die Bahn?", "проездной билет", "У вас есть действующий билет на поезд?", "ticket (transit)", "Do you have a valid train ticket?"),
    ("Bahnsteig", "der", "die Bahnsteige", "A1", "Reise", "Der Zug fährt von Bahnsteig vier ab.", "железнодорожная платформа", "Поезд отправляется с четвертой платформы.", "platform (train)", "The train departs from platform four."),
    ("Gleis", "das", "die Gleise", "A1", "Reise", "Vorsicht an Gleis zwei, der Zug fährt ein.", "железнодорожный путь", "Осторожно на втором пути, поезд прибывает.", "track / platform", "Attention on track two, the train is arriving."),
    ("Gepäck", "das", "die Gepäcke", "A1", "Reise", "Das Gepäck wiegt mehr als zwanzig Kilo.", "багаж", "Багаж весит больше двадцати килограммов.", "luggage / baggage", "The luggage weighs more than twenty kilos."),
    ("Koffer", "der", "die Koffer", "A1", "Reise", "Ich packe meinen Koffer für den Urlaub.", "чемодан", "Я собираю свой чемодан в отпуск.", "suitcase", "I am packing my suitcase for vacation."),
    ("Hotel", "das", "die Hotels", "A1", "Reise", "Das Hotel liegt direkt am Meer.", "отель / гостиница", "Отель расположен прямо у моря.", "hotel", "The hotel is located right by the sea."),
    ("Rezeption", "die", "die Rezeptionen", "A1", "Reise", "Der Schlüssel liegt an der Rezeption bereit.", "стойка регистрации", "Ключ ждет на стойке регистрации.", "reception desk", "The key is ready at the reception desk."),
    ("Zimmer", "das", "die Zimmer", "A1", "Reise", "Wir haben ein ruhiges Zimmer mit Balkon gebucht.", "комната / номер", "Мы забронировали тихий номер с балконом.", "room", "We booked a quiet room with a balcony."),
    ("Schlüssel", "der", "die Schlüssel", "A1", "Reise", "Geben Sie den Schlüssel beim Auschecken ab.", "ключ", "Сдайте ключ при выезде.", "key", "Hand in the key when checking out."),
    ("Strand", "der", "die Strände", "A1", "Reise", "Am Strand liegen viele bunte Sonnenschirme.", "пляж", "На пляже стоит много цветных зонтиков.", "beach", "Many colorful umbrellas are on the beach."),
    ("Meer", "das", "die Meere", "A1", "Reise", "Das Wasser im Meer ist heute angenehm warm.", "море", "Вода в море сегодня приятно теплая.", "sea / ocean", "The water in the sea is pleasantly warm today."),
    ("Insel", "die", "die Inseln", "A1", "Reise", "Rügen ist die größte Insel Deutschlands.", "остров", "Рюген - самый большой остров Германии.", "island", "Rügen is Germany's largest island."),
    ("Berg", "der", "die Berge", "A1", "Reise", "Im Winter sind die Spitzen der Berge weiß.", "гора", "Зимой вершины гор белые.", "mountain", "In winter the mountain peaks are white."),
    ("See", "der", "die Seen", "A1", "Reise", "Wir schwimmen gern im See neben unserem Dorf.", "озеро", "Мы любим плавать в озере рядом с нашей деревней.", "lake", "We enjoy swimming in the lake next to our village."),
    ("Ausflug", "der", "die Ausflüge", "A2", "Reise", "Am Wochenende machen wir einen Ausflug ins Grüne.", "экскурсия / вылазка", "На выходных мы совершим загородную прогулку.", "excursion / day trip", "At the weekend we go on a day trip into the countryside."),
    ("Stadtplan", "der", "die Stadtpläne", "A1", "Reise", "Auf dem Stadtplan suchen wir die Altstadt.", "карта города", "На карте города мы ищем старый город.", "city map", "On the city map we look for the old town."),
    ("Souvenir", "das", "die Souvenirs", "A2", "Reise", "Sie kaufte ein schönes Souvenir für ihre Schwester.", "сувенир", "Она купила красивый сувенир для сестры.", "souvenir", "She bought a nice souvenir for her sister."),
    ("Abfahrt", "die", "die Abfahrten", "A1", "Reise", "Die Abfahrt des Zuges ist pünktlich um zehn.", "отправление", "Отправление поезда ровно в десять.", "departure", "The train's departure is on time at ten."),
    ("Ankunft", "die", "die Ankünfte", "A1", "Reise", "Die genaue Ankunft wird auf der Anzeige gezeigt.", "прибытие", "Точное время прибытия указано на табло.", "arrival", "The exact arrival is shown on the display."),
    ("Verspätung", "die", "die Verspätungen", "A1", "Reise", "Der ICE hat zwanzig Minuten Verspätung.", "опоздание / задержка", "Поезд ICE задерживается на двадцать минут.", "delay", "The ICE train has a twenty-minute delay."),
    ("Grenze", "die", "die Grenzen", "A2", "Reise", "An der Grenze gab es keine Passkontrolle.", "граница", "На границе не было паспортного контроля.", "border", "At the border there was no passport control."),
    ("Zoll", "der", "die Zölle", "B1", "Reise", "Beim Zoll muss man teure Waren anmelden.", "таможня", "На таможне необходимо декларировать дорогие товары.", "customs", "At customs you have to declare expensive goods."),
    ("Visum", "das", "die Visa", "A2", "Reise", "Für diese Reise brauche ich ein gültiges Visum.", "виза", "Для этой поездки мне нужна действующая виза.", "visa", "For this trip I need a valid visa."),
    ("Schalter", "der", "die Schalter", "A2", "Reise", "Kaufen Sie die Fahrkarte am Schalter oder Automat.", "касса / окно обслуживания", "Купите билет в кассе или автомате.", "ticket window / counter", "Buy the ticket at the counter or ticket machine."),
    ("Gast", "der", "die Gäste", "A1", "Reise", "Das Hotel begrüßt jeden neuen Gast herzlich.", "гость", "Отель тепло приветствует каждого нового гостя.", "guest", "The hotel warmly welcomes each new guest."),
    ("Urlaub", "der", "die Urlaube", "A1", "Reise", "Nächste Woche fahre ich endlich in den Urlaub.", "отпуск", "На следующей неделе я наконец уезжаю в отпуск.", "vacation / holiday", "Next week I am finally going on vacation."),
    ("Tourist", "der", "die Touristen", "A1", "Reise", "Viele Touristen fotografieren das Brandenburger Tor.", "турист", "Многие туристы фотографируют Бранденбургские ворота.", "tourist", "Many tourists photograph the Brandenburg Gate."),
    ("Fähre", "die", "die Fähren", "A2", "Reise", "Die Fähre bringt Autos über den großen Fluss.", "паром", "Паром перевозит автомобили через большую реку.", "ferry", "The ferry carries cars across the large river."),
    ("Hafen", "der", "die Häfen", "A2", "Reise", "Im Hamburger Hafen liegen viele Frachtschiffe.", "порт / гавань", "В гамбургском порту стоит много грузовых судов.", "harbor / port", "In Hamburg harbor there are many cargo ships."),
    ("Kreuzfahrt", "die", "die Kreuzfahrten", "B1", "Reise", "Meine Großeltern machten eine Kreuzfahrt im Mittelmeer.", "морской круиз", "Мои бабушка и дедушка отправились в круиз по Средиземному морю.", "cruise", "My grandparents took a cruise in the Mediterranean."),
    ("Autobahn", "die", "die Autobahnen", "A1", "Reise", "Auf der Autobahn gibt es heute einen langen Stau.", "автомагистраль / автобан", "На автобане сегодня длинная пробка.", "highway / autobahn", "On the autobahn there is a long traffic jam today."),
    ("Tankstelle", "die", "die Tankstellen", "A1", "Reise", "An der Tankstelle füllen wir Benzin nach.", "заправка (АЗС)", "На заправке мы заливаем бензин.", "gas station", "At the gas station we refill gasoline."),
    ("Raststätte", "die", "die Raststätten", "A2", "Reise", "An der Raststätte trinken wir einen Kaffee.", "придорожное кафе / зона отдыха", "В зоне отдыха у дороги мы пьем кофе.", "rest stop", "At the rest stop we drink a coffee."),
    ("Aussicht", "die", "die Aussichten", "A2", "Reise", "Vom Turm hat man eine herrliche Aussicht.", "вид / панорама", "С башни открывается великолепный вид.", "view / outlook", "From the tower you have a magnificent view."),
    ("Reiseziel", "das", "die Reiseziele", "A2", "Reise", "Italien ist seit Jahren unser liebstes Reiseziel.", "пункт назначения / направление", "Италия уже много лет - наше любимое направление для поездок.", "destination", "Italy has been our favorite travel destination for years."),
    ("Reiseführer", "der", "die Reiseführer", "A2", "Reise", "Im Reiseführer stehen nützliche Tipps für Touristen.", "путеводитель / гид", "В путеводителе собраны полезные советы для туристов.", "guidebook / tour guide", "The guidebook contains useful tips for tourists."),
    ("Sehenswürdigkeit", "die", "die Sehenswürdigkeiten", "A2", "Reise", "Der Kölner Dom ist eine berühmte Sehenswürdigkeit.", "достопримечательность", "Кельнский собор - знаменитая достопримечательность.", "sight / attraction", "Cologne Cathedral is a famous attraction."),
    ("Rundfahrt", "die", "die Rundfahrten", "A2", "Reise", "Wir buchen eine zweistündige Rundfahrt durch die Stadt.", "обзорная экскурсия", "Мы бронируем двухчасовую обзорную поездку по городу.", "sightseeing tour", "We book a two-hour sightseeing tour of the city."),
    ("Haltestelle", "die", "die Haltestellen", "A1", "Reise", "Der Bus hält an der nächsten Haltestelle.", "остановка", "Автобус остановится на следующей остановке.", "bus stop / station", "The bus stops at the next stop."),
    ("Mietwagen", "der", "die Mietwagen", "A2", "Reise", "Am Flughafen holten wir unseren Mietwagen ab.", "арендованный автомобиль", "В аэропорту мы забрали наш прокатный автомобиль.", "rental car", "At the airport we picked up our rental car."),

    # --- KLEIDUNG & MODE (Одежда и мода) ---
    ("Hose", "die", "die Hosen", "A1", "Kleidung", "Diese schwarze Hose passt mir sehr gut.", "брюки / штаны", "Эти черные брюки сидят на мне очень хорошо.", "trousers / pants", "These black trousers fit me very well."),
    ("Jeans", "die", "die Jeans", "A1", "Kleidung", "Er trägt am liebsten eine bequeme Jeans.", "джинсы", "Он больше всего любит носить удобные джинсы.", "jeans", "He prefers wearing comfortable jeans."),
    ("Hemd", "das", "die Hemden", "A1", "Kleidung", "Zum Vorstellungsgespräch trage ich ein weißes Hemd.", "рубашка", "На собеседование я надеваю белую рубашку.", "shirt", "For the job interview I wear a white shirt."),
    ("T-Shirt", "das", "die T-Shirts", "A1", "Kleidung", "Im Sommer trage ich bunte T-Shirts.", "футболка", "Летом я ношу цветные футболки.", "t-shirt", "In summer I wear colorful t-shirts."),
    ("Pullover", "der", "die Pullover", "A1", "Kleidung", "Der Pullover aus Wolle hält mich schön warm.", "свитер", "Шерстяной свитер отлично согревает меня.", "sweater / pullover", "The woolen sweater keeps me nicely warm."),
    ("Jacke", "die", "die Jacken", "A1", "Kleidung", "Zieh deine warme Jacke an, draußen ist es kalt.", "куртка", "Надень теплую куртку, на улице холодно.", "jacket", "Put on your warm jacket, it is cold outside."),
    ("Mantel", "der", "die Mäntel", "A1", "Kleidung", "Der lange Mantel schützt vor starkem Wind.", "пальто", "Длинное пальто защищает от сильного ветра.", "coat", "The long coat protects against strong wind."),
    ("Kleid", "das", "die Kleider", "A1", "Kleidung", "Sie kaufte ein elegantes rotes Kleid für die Oper.", "платье", "Она купила элегантное красное платье для оперы.", "dress", "She bought an elegant red dress for the opera."),
    ("Rock", "der", "die Röcke", "A1", "Kleidung", "Der blaue Rock passt gut zu ihrer Bluse.", "юбка", "Синяя юбка хорошо сочетается с ее блузкой.", "skirt", "The blue skirt matches her blouse well."),
    ("Bluse", "die", "die Blusen", "A1", "Kleidung", "Die seidige Bluse fühlt sich sehr weich an.", "блузка", "Шелковая блузка очень мягкая на ощупь.", "blouse", "The silk blouse feels very soft."),
    ("Anzug", "der", "die Anzüge", "A2", "Kleidung", "Zur Hochzeit zog er einen dunklen Anzug an.", "деловой костюм", "На свадьбу он надел темный костюм.", "suit", "For the wedding he put on a dark suit."),
    ("Krawatte", "die", "die Krawatten", "A2", "Kleidung", "Er bindet seine Krawatte vor dem Spiegel.", "галстук", "Он завязывает галстук перед зеркалом.", "tie / necktie", "He ties his necktie in front of the mirror."),
    ("Gürtel", "der", "die Gürtel", "A1", "Kleidung", "Der lederne Gürtel hält die Hose fest.", "ремень / пояс", "Кожаный ремень надежно держит брюки.", "belt", "The leather belt holds the trousers tight."),
    ("Schal", "der", "die Schals", "A1", "Kleidung", "Im Winter binde ich mir einen dicken Schal um.", "шарф", "Зимой я повязываю толстый шарф.", "scarf", "In winter I tie a thick scarf around my neck."),
    ("Mütze", "die", "die Mützen", "A1", "Kleidung", "Vergiss deine Mütze nicht, es schneit draußen.", "шапка", "Не забудь шапку, на улице идет снег.", "beanie / warm cap", "Do not forget your cap, it is snowing outside."),
    ("Hut", "der", "die Hüte", "A1", "Kleidung", "Der alte Herr trägt einen eleganten Hut.", "шляпа", "Пожилой господин носит элегантную шляпу.", "hat", "The elderly gentleman wears an elegant hat."),
    ("Handschuh", "der", "die Handschuhe", "A1", "Kleidung", "Ohne Handschuhe frieren mir die Finger ein.", "перчатка", "Без перчаток у меня замерзают пальцы.", "glove", "Without gloves my fingers freeze."),
    ("Socke", "die", "die Socken", "A1", "Kleidung", "Ich ziehe mir frische Socken an.", "носок", "Я надеваю чистые носки.", "sock", "I put on clean socks."),
    ("Schuh", "der", "die Schuhe", "A1", "Kleidung", "Zieh bitte deine Schuhe im Flur aus.", "туфля / обувь", "Сними, пожалуйста, обувь в прихожей.", "shoe", "Please take off your shoes in the hallway."),
    ("Stiefel", "der", "die Stiefel", "A1", "Kleidung", "Im Matsch brauche ich feste Stiefel.", "сапог / ботинок", "В слякоть мне нужны прочные сапоги.", "boot", "In the mud I need sturdy boots."),
    ("Turnschuh", "der", "die Turnschuhe", "A2", "Kleidung", "Für den Sportunterricht braucht er Turnschuhe.", "кроссовок / кед", "Для физкультуры ему нужны кроссовки.", "sneaker / trainer", "For PE class he needs sneakers."),
    ("Hausschuh", "der", "die Hausschuhe", "A2", "Kleidung", "Zu Hause trage ich warme Hausschuhe.", "домашний тапочек", "Дома я ношу теплые тапочки.", "slipper", "At home I wear warm slippers."),
    ("Sandale", "die", "die Sandalen", "A2", "Kleidung", "Im heißen Sommer laufe ich gern in Sandalen.", "сандалия", "Жарким летом я люблю ходить в сандалиях.", "sandal", "In hot summer I like walking in sandals."),
    ("Regenmantel", "der", "die Regenmäntel", "A2", "Kleidung", "Bei starkem Regen hilft nur ein Regenmantel.", "дождевик", "В сильный дождь помогает только дождевик.", "raincoat", "In heavy rain only a raincoat helps."),
    ("Regenschirm", "der", "die Regenschirme", "A1", "Kleidung", "Ich habe meinen Regenschirm im Bus vergessen.", "зонт от дождя", "Я забыл свой зонт в автобусе.", "umbrella", "I forgot my umbrella on the bus."),
    ("Brille", "die", "die Brillen", "A1", "Kleidung", "Ohne meine Brille kann ich das Buch nicht lesen.", "очки", "Без очков я не могу прочитать эту книгу.", "glasses", "Without my glasses I cannot read the book."),
    ("Sonnenbrille", "die", "die Sonnenbrillen", "A1", "Kleidung", "Im Sommer schützt die Sonnenbrille meine Augen.", "солнцезащитные очки", "Летом солнцезащитные очки защищают мои глаза.", "sunglasses", "In summer sunglasses protect my eyes."),
    ("Schmuck", "der", "die Schmucke", "A2", "Kleidung", "Sie liebt feinen Schmuck aus Silber.", "украшения / ювелирные изделия", "Она любит изящные украшения из серебра.", "jewelry", "She loves fine silver jewelry."),
    ("Ring", "der", "die Ringe", "A1", "Kleidung", "Der goldene Ring glänzt am Finger.", "кольцо", "Золотое кольцо блестит на пальце.", "ring", "The golden ring shines on the finger."),
    ("Kette", "die", "die Ketten", "A2", "Kleidung", "Sie trägt eine schöne Kette um den Hals.", "цепочка / колье", "Она носит красивую цепочку на шее.", "necklace / chain", "She wears a nice necklace around her neck."),
    ("Armband", "das", "die Armbänder", "A2", "Kleidung", "Das lederne Armband war ein Geschenk meines Freundes.", "браслет", "Кожаный браслет был подарком моего друга.", "bracelet", "The leather bracelet was a gift from my friend."),
    ("Ohrring", "der", "die Ohrringe", "A2", "Kleidung", "Sie kaufte sich funkelnde Ohrringe.", "серьга", "Она купила себе сверкающие серьги.", "earring", "She bought herself sparkling earrings."),
    ("Uhr", "die", "die Uhren", "A1", "Kleidung", "Meine Uhr zeigt genau zwölf Uhr mittags.", "часы", "Мои часы показывают ровно двенадцать часов дня.", "watch / clock", "My watch shows exactly twelve noon."),
    ("Armbanduhr", "die", "die Armbanduhren", "A2", "Kleidung", "Er trägt eine elegante Armbanduhr aus Stahl.", "наручные часы", "Он носит элегантные наручные часы из стали.", "wristwatch", "He wears an elegant wristwatch made of steel."),
    ("Handtasche", "die", "die Handtaschen", "A1", "Kleidung", "In der Handtasche hat sie Geld und Schlüssel.", "дамская сумочка", "В сумочке у нее деньги и ключи.", "handbag / purse", "In her handbag she has money and keys."),
    ("Geldbörse", "die", "die Geldbörsen", "A1", "Kleidung", "Ich habe meine Geldbörse auf den Tisch gelegt.", "кошелек", "Я положил свой кошелек на стол.", "wallet / purse", "I put my wallet on the table."),
    ("Reißverschluss", "der", "die Reißverschlüsse", "B1", "Kleidung", "Der Reißverschluss an der Jacke klemmt leider.", "застежка-молния", "Молния на куртке, к сожалению, заедает.", "zipper", "The zipper on the jacket is unfortunately stuck."),
    ("Knopf", "der", "die Knöpfe", "A2", "Kleidung", "Der Knopf am Hemd ist abgefallen.", "пуговица", "Пуговица на рубашке оторвалась.", "button", "The button on the shirt fell off."),
    ("Tasche", "die", "die Taschen", "A1", "Kleidung", "Ich stecke das Smartphone in die Tasche.", "карман / сумка", "Я кладу смартфон в карман.", "pocket / bag", "I put the smartphone into my pocket."),
    ("Kragen", "der", "die Kragen", "B1", "Kleidung", "Er stellte den Kragen seiner Jacke gegen den Wind auf.", "воротник", "Он поднял воротник куртки против ветра.", "collar", "He put up the collar of his jacket against the wind."),
    ("Stoff", "der", "die Stoffe", "A2", "Kleidung", "Dieser Stoff ist aus reiner Baumwolle.", "ткань / материал", "Эта ткань изготовлена из чистого хлопка.", "fabric / cloth", "This fabric is made of pure cotton."),
    ("Baumwolle", "die", "die Baumwollen", "A2", "Kleidung", "Kleidung aus Baumwolle schwitzt man weniger.", "хлопок", "В одежде из хлопка меньше потеют.", "cotton", "In cotton clothing you sweat less."),
    ("Wolle", "die", "die Wollen", "A2", "Kleidung", "Echte Wolle hält im Winter am wärmsten.", "шерсть", "Натуральная шерсть греет лучше всего зимой.", "wool", "Real wool keeps you warmest in winter."),
    ("Seide", "die", "die Seiden", "B1", "Kleidung", "Das Kleid aus Seide fühlt sich herrlich an.", "шелк", "Платье из шелка ощущается восхитительно.", "silk", "The silk dress feels wonderful."),
    ("Leder", "das", "die Leder", "A2", "Kleidung", "Diese Jacke ist aus echtem Leder gemacht.", "кожа (материал)", "Эта куртка сделана из натуральной кожи.", "leather", "This jacket is made of genuine leather."),
    ("Schlafanzug", "der", "die Schlafanzüge", "A2", "Kleidung", "Vor dem Schlafen ziehe ich meinen Schlafanzug an.", "пижама", "Перед сном я надеваю свою пижаму.", "pajamas", "Before sleeping I put on my pajamas."),
    ("Unterwäsche", "die", "die Unterwäschen", "A2", "Kleidung", "Frische Unterwäsche liegt im Kleiderschrank.", "нижнее белье", "Чистое нижнее белье лежит в шкафу.", "underwear", "Fresh underwear is in the wardrobe."),
    ("Bademantel", "der", "die Bademäntel", "A2", "Kleidung", "Nach der Dusche ziehe ich den weichen Bademantel an.", "банный халат", "После душа я надеваю мягкий банный халат.", "bathrobe", "After the shower I put on the soft bathrobe."),
    ("Badeanzug", "der", "die Badeanzüge", "A2", "Kleidung", "Für das Schwimmbad braucht sie einen Badeanzug.", "купальник", "Для бассейна ей нужен купальник.", "swimsuit", "For the swimming pool she needs a swimsuit."),
    ("Badehose", "die", "die Badehosen", "A2", "Kleidung", "Im Sommerurlaub trage ich meine Badehose am Strand.", "плавки", "В летнем отпуске я ношу плавки на пляже.", "swimming trunks", "On summer vacation I wear my swimming trunks at the beach."),

    # --- GESUNDHEIT & KÖRPER (Здоровье и тело) ---
    ("Krankenhaus", "das", "die Krankenhäuser", "A1", "Gesundheit", "Der Arzt arbeitet im städtischen Krankenhaus.", "больница", "Врач работает в городской больнице.", "hospital", "The doctor works in the municipal hospital."),
    ("Klinik", "die", "die Kliniken", "A2", "Gesundheit", "Die private Klinik bietet moderne Behandlungen.", "клиника", "Частная клиника предлагает современные методы лечения.", "clinic", "The private clinic offers modern treatments."),
    ("Praxis", "die", "die Praxen", "A2", "Gesundheit", "Die Arztpraxis öffnet morgens um acht Uhr.", "кабинет врача / приемная", "Приемная врача открывается утром в восемь часов.", "doctor's practice", "The doctor's practice opens at 8 am in the morning."),
    ("Apotheke", "die", "die Apotheken", "A1", "Gesundheit", "In der Apotheke kaufe ich Schmerzmittel.", "аптека", "В аптеке я покупаю обезболивающие.", "pharmacy", "In the pharmacy I buy painkillers."),
    ("Medikament", "das", "die Medikamente", "A1", "Gesundheit", "Nehmen Sie dieses Medikament dreimal täglich.", "лекарство", "Принимайте это лекарство три раза в день.", "medication / medicine", "Take this medication three times a day."),
    ("Tablette", "die", "die Tabletten", "A1", "Gesundheit", "Trinken Sie ein Glas Wasser zur Tablette.", "таблетка", "Запейте таблетку стаканом воды.", "pill / tablet", "Drink a glass of water with the tablet."),
    ("Pille", "die", "die Pillen", "A2", "Gesundheit", "Die kleine Pille hilft schnell gegen Kopfschmerzen.", "пилюля", "Маленькая пилюля быстро помогает от головной боли.", "pill", "The small pill quickly helps against headache."),
    ("Salbe", "die", "die Salben", "A2", "Gesundheit", "Tragen Sie die heilende Salbe dünn auf die Haut auf.", "мазь", "Нанесите целебную мазь тонким слоем на кожу.", "ointment", "Apply the healing ointment thinly to the skin."),
    ("Tropfen", "die", "die Tropfen", "A2", "Gesundheit", "Der Arzt verschrieb ihr Augentropfen.", "капли (лекарственные)", "Врач прописал ей глазные капли.", "drops", "The doctor prescribed eye drops for her."),
    ("Rezept", "das", "die Rezepte", "A1", "Gesundheit", "Für manche Medikamente braucht man ein Rezept vom Arzt.", "рецепт (медицинский)", "Для некоторых лекарств нужен рецепт от врача.", "prescription", "For some medications you need a doctor's prescription."),
    ("Pflaster", "das", "die Pflaster", "A1", "Gesundheit", "Kleben Sie ein Pflaster auf den Schnitt am Finger.", "пластырь", "Наклейте пластырь на порез на пальце.", "band-aid / plaster", "Stick a plaster on the cut on your finger."),
    ("Verband", "der", "die Verbände", "A2", "Gesundheit", "Die Krankenschwester wechselt den Verband am Arm.", "бинт / повязка", "Медсестра меняет повязку на руке.", "bandage / dressing", "The nurse changes the bandage on the arm."),
    ("Spritze", "die", "die Spritzen", "A2", "Gesundheit", "Viele Kinder haben Angst vor einer Spritze.", "укол / шприц", "Многие дети боятся укола.", "injection / syringe", "Many children are afraid of an injection."),
    ("Schmerz", "der", "die Schmerzen", "A1", "Gesundheit", "Der Schmerz im Knie wird langsam schwächer.", "боль", "Боль в колене постепенно стихает.", "pain", "The pain in the knee is slowly getting weaker."),
    ("Kopfschmerz", "der", "die Kopfschmerzen", "A1", "Gesundheit", "Gegen Kopfschmerzen trinke ich viel Wasser.", "головная боль", "От головной боли я пью много воды.", "headache", "Against headaches I drink a lot of water."),
    ("Bauchschmerz", "der", "die Bauchschmerzen", "A1", "Gesundheit", "Nach zu viel Essen bekam er Bauchschmerzen.", "боль в животе", "После переедания у него заболел живот.", "stomachache", "After eating too much he got stomach pains."),
    ("Halsschmerz", "der", "die Halsschmerzen", "A1", "Gesundheit", "Warmer Tee mit Honig lindert Halsschmerzen.", "боль в горле", "Теплый чай с медом облегчает боль в горле.", "sore throat", "Warm tea with honey relieves sore throat."),
    ("Fieber", "das", "die Fieber", "A1", "Gesundheit", "Er hat hohes Fieber und muss im Bett bleiben.", "температура / жар", "У него высокая температура, и он должен оставаться в постели.", "fever", "He has a high fever and must stay in bed."),
    ("Husten", "der", "die Husten", "A1", "Gesundheit", "Der trockene Husten stört mich beim Schlafen.", "кашель", "Сухой кашель мешает мне спать.", "cough", "The dry cough bothers me while sleeping."),
    ("Schnupfen", "der", "die Schnupfen", "A1", "Gesundheit", "Bei Schnupfen brauche ich viele Papiertaschentücher.", "насморк", "При насморке мне нужно много бумажных платков.", "runny nose / cold", "With a cold I need many tissues."),
    ("Grippe", "die", "die Grippen", "A2", "Gesundheit", "Im Winter haben viele Menschen eine echte Grippe.", "грипп", "Зимой многие люди болеют настоящим гриппом.", "flu / influenza", "In winter many people have real flu."),
    ("Erkältung", "die", "die Erkältungen", "A1", "Gesundheit", "Eine heiße Suppe ist das beste Mittel gegen Erkältung.", "простуда", "Горячий суп - лучшее средство от простуды.", "common cold", "A hot soup is the best remedy for a cold."),
    ("Wunde", "die", "die Wunden", "A2", "Gesundheit", "Die Wunde am Knie heilt erstaunlich schnell.", "рана", "Рана на колене заживает удивительно быстро.", "wound", "The wound on the knee heals remarkably quickly."),
    ("Verletzung", "die", "die Verletzungen", "B1", "Gesundheit", "Nach dem Unfall hatte er glücklicherweise keine Verletzung.", "травма / повреждение", "После аварии у него, к счастью, не было травм.", "injury", "After the accident he fortunately had no injury."),
    ("Unfall", "der", "die Unfälle", "A1", "Gesundheit", "Auf der Kreuzung passierte ein kleiner Unfall.", "несчастный случай / авария", "На перекрестке произошла небольшая авария.", "accident", "A small accident happened at the intersection."),
    ("Krankenwagen", "der", "die Krankenwagen", "A1", "Gesundheit", "Der Krankenwagen kam mit lautem Martinshorn.", "машина скорой помощи", "Скорая помощь приехала с громкой сиреной.", "ambulance", "The ambulance arrived with a loud siren."),
    ("Notaufnahme", "die", "die Notaufnahmen", "A2", "Gesundheit", "Im Notfall fährt man direkt in die Notaufnahme.", "отделение неотложной помощи", "В экстренном случае едут прямо в приемный покой.", "emergency room", "In an emergency you drive directly to the emergency room."),
    ("Krankenkasse", "die", "die Krankenkassen", "A2", "Gesundheit", "Die deutsche Krankenkasse übernimmt die Arztkosten.", "больничная касса / медстраховка", "Немецкая больничная касса покрывает расходы на врача.", "health insurance fund", "The German health insurance covers the medical costs."),
    ("Untersuchung", "die", "die Untersuchungen", "A2", "Gesundheit", "Die gründliche Untersuchung dauerte eine halbe Stunde.", "осмотр / обследование", "Тщательное обследование длилось полчаса.", "examination / checkup", "The thorough examination took half an hour."),
    ("Behandlung", "die", "die Behandlungen", "B1", "Gesundheit", "Die Behandlung zeigte schon nach drei Tagen Erfolg.", "лечение", "Лечение дало результат уже через три дня.", "treatment", "The treatment showed success after just three days."),
    ("Operation", "die", "die Operationen", "A2", "Gesundheit", "Die schwierige Operation verlief ohne Komplikationen.", "операция", "Сложная операция прошла без осложнений.", "surgery / operation", "The difficult operation went without complications."),
    ("Pflege", "die", "die Pflegen", "B1", "Gesundheit", "Gute Pflege hilft kranken Menschen bei der Genesung.", "уход за больными", "Хороший уход помогает больным людям выздороветь.", "care / nursing", "Good care helps sick people recover."),
    ("Körper", "der", "die Körper", "A1", "Gesundheit", "Sport und gesunde Ernährung stärken den Körper.", "тело / организм", "Спорт и здоровое питание укрепляют тело.", "body", "Sports and healthy nutrition strengthen the body."),
    ("Blut", "das", "die Blute", "A2", "Gesundheit", "Der Arzt nimmt Blut für ein Laborbild ab.", "кровь", "Врач берет кровь для анализа.", "blood", "The doctor takes blood for a lab panel."),
    ("Herz", "das", "die Herzen", "A1", "Gesundheit", "Das Herz schlägt bei Aufregung schneller.", "сердце", "Сердце бьется быстрее при волнении.", "heart", "The heart beats faster when excited."),
    ("Lunge", "die", "die Lungen", "A2", "Gesundheit", "Frische Luft im Wald ist gut für die Lunge.", "легкие", "Свежий воздух в лесу полезен для легких.", "lung", "Fresh air in the forest is good for the lungs."),
    ("Magen", "der", "die Magen", "A2", "Gesundheit", "Mein Magen knurrt, weil ich Hunger habe.", "желудок", "В моем желудке урчит, потому что я голоден.", "stomach", "My stomach is growling because I am hungry."),
    ("Gehirn", "das", "die Gehirne", "B1", "Gesundheit", "Das Gehirn braucht Sauerstoff zum Denken.", "мозг", "Мозгу нужен кислород для мышления.", "brain", "The brain needs oxygen to think."),
    ("Knochen", "der", "die Knochen", "A2", "Gesundheit", "Milch liefert Kalzium für starke Knochen.", "кость", "Молоко дает кальций для крепких костей.", "bone", "Milk provides calcium for strong bones."),
    ("Muskel", "der", "die Muskeln", "A2", "Gesundheit", "Nach dem harten Training schmerzt jeder Muskel.", "мышца", "После тяжелой тренировки болит каждая мышца.", "muscle", "After the hard training every muscle aches."),
    ("Haut", "die", "die Häute", "A1", "Gesundheit", "Sonnencreme schützt die empfindliche Haut.", "кожа (человека)", "Солнцезащитный крем защищает чувствительную кожу.", "skin", "Sunscreen protects the sensitive skin."),
    ("Zahn", "der", "die Zähne", "A1", "Gesundheit", "Putze dir zweimal täglich gründlich die Zähne.", "зуб", "Чисти зубы тщательно дважды в день.", "tooth", "Brush your teeth thoroughly twice a day."),
    ("Zahnarzt", "der", "die Zahnärzte", "A1", "Gesundheit", "Ich habe morgen einen Kontrolltermin beim Zahnarzt.", "зубной врач / стоматолог", "У меня завтра осмотр у стоматолога.", "dentist", "I have a checkup appointment with the dentist tomorrow."),
    ("Kopf", "der", "die Köpfe", "A1", "Gesundheit", "Er schüttelt nachdenklich den Kopf.", "голова", "Он задумчиво качает головой.", "head", "He shakes his head thoughtfully."),
    ("Auge", "das", "die Augen", "A1", "Gesundheit", "Sie hat wunderschöne blaue Augen.", "глаз", "У нее прекрасные голубые глаза.", "eye", "She has beautiful blue eyes."),
    ("Ohr", "das", "die Ohren", "A1", "Gesundheit", "Halt dir bei dem lauten Lärm die Ohren zu.", "ухо", "Заткни уши от этого громкого шума.", "ear", "Cover your ears in that loud noise."),
    ("Nase", "die", "die Nasen", "A1", "Gesundheit", "Ich rieche den Duft von frischem Kaffee mit der Nase.", "нос", "Я чувствую запах свежего кофе носом.", "nose", "I smell the scent of fresh coffee with my nose."),
    ("Mund", "der", "die Münder", "A1", "Gesundheit", "Öffnen Sie bitte weit den Mund, sagt der Arzt.", "рот", "Откройте, пожалуйста, широко рот, говорит врач.", "mouth", "Please open your mouth wide, says the doctor."),
    ("Hals", "der", "die Hälse", "A1", "Gesundheit", "Wickle dir bei Kälte einen Schal um den Hals.", "шея / горло", "В холод обмотай шарф вокруг шеи.", "neck / throat", "Wrap a scarf around your neck in the cold."),
    ("Rücken", "der", "die Rücken", "A1", "Gesundheit", "Ein guter Bürostuhl schont den Rücken.", "спина", "Хорошее офисное кресло бережет спину.", "back", "A good office chair is gentle on your back."),
    ("Bauch", "der", "die Bäuche", "A1", "Gesundheit", "Das Kind schläft am liebsten auf dem Bauch.", "живот", "Ребенок больше всего любит спать на животе.", "belly / stomach", "The child prefers sleeping on their belly."),
    ("Arm", "der", "die Arme", "A1", "Gesundheit", "Er hob das Kind mit beiden Armen hoch.", "рука (от плеча до кисти)", "Он поднял ребенка обеими руками.", "arm", "He lifted the child up with both arms."),
    ("Hand", "die", "die Hände", "A1", "Gesundheit", "Wasch dir vor dem Essen gründlich die Hände.", "кисть руки / рука", "Мой руки тщательно перед едой.", "hand", "Wash your hands thoroughly before eating."),
    ("Finger", "der", "die Finger", "A1", "Gesundheit", "An jeder Hand haben wir fünf Finger.", "палец на руке", "На каждой руке у нас по пять пальцев.", "finger", "On each hand we have five fingers."),
    ("Bein", "das", "die Beine", "A1", "Gesundheit", "Nach dem langen Spaziergang tun mir die Beine weh.", "нога", "После долгой прогулки у меня болят ноги.", "leg", "After the long walk my legs hurt."),
    ("Fuß", "der", "die Füße", "A1", "Gesundheit", "Wir gehen den ganzen Weg zu Fuß.", "стопа / нога", "Мы идем весь путь пешком.", "foot", "We walk the whole way on foot."),

    # --- LERNEN & WISSEN (Учеба и знания) ---
    ("Klassenzimmer", "das", "die Klassenzimmer", "A1", "Lernen", "Im Klassenzimmer stehen dreißig Tische.", "классная комната / класс", "В классе стоит тридцать парт.", "classroom", "Thirty desks stand in the classroom."),
    ("Klasse", "die", "die Klassen", "A1", "Lernen", "Mein Sohn geht jetzt in die vierte Klasse.", "класс (группа/год обучения)", "Мой сын сейчас ходит в четвертый класс.", "class / grade", "My son is now in fourth grade."),
    ("Schüler", "der", "die Schüler", "A1", "Lernen", "Die Schüler hören der Lehrerin aufmerksam zu.", "ученик / школьник", "Ученики внимательно слушают учительницу.", "pupil / school student", "The pupils listen attentively to the teacher."),
    ("Student", "der", "die Studenten", "A1", "Lernen", "Als Student lernt man viel in der Bibliothek.", "студент", "Будучи студентом, много учишься в библиотеке.", "university student", "As a student you study a lot in the library."),
    ("Professor", "der", "die Professoren", "A2", "Lernen", "Der Professor hält eine Vorlesung über Geschichte.", "профессор", "Профессор читает лекцию по истории.", "professor", "The professor gives a lecture on history."),
    ("Lehrbuch", "das", "die Lehrbücher", "A1", "Lernen", "Wir schlagen das Lehrbuch auf Seite zehn auf.", "учебник", "Мы открываем учебник на странице десять.", "textbook", "We open the textbook on page ten."),
    ("Heft", "das", "die Hefte", "A1", "Lernen", "Schreibe die Vokabeln sauber in dein Heft.", "тетрадь", "Запиши слова аккуратно в свою тетрадь.", "notebook / exercise book", "Write the vocabulary neatly into your notebook."),
    ("Notizbuch", "das", "die Notizbücher", "A1", "Lernen", "Ich trage wichtige Termine in mein Notizbuch ein.", "блокнот", "Я записываю важные встречи в свой блокнот.", "notebook", "I enter important dates into my notebook."),
    ("Stift", "der", "die Stifte", "A1", "Lernen", "Darf ich mir kurz deinen Stift leihen?", "ручка / карандаш", "Могу я одолжить ненадолго твою ручку?", "pen / pencil", "May I briefly borrow your pen?"),
    ("Bleistift", "der", "die Bleistifte", "A1", "Lernen", "Zeichnungen macht man am besten mit dem Bleistift.", "карандаш", "Рисунки лучше всего делать простым карандашом.", "pencil", "Drawings are best made with a pencil."),
    ("Kugelschreiber", "der", "die Kugelschreiber", "A1", "Lernen", "Unterschreiben Sie den Vertrag mit blauem Kugelschreiber.", "шариковая ручка", "Подпишите договор синей шариковой ручкой.", "ballpoint pen", "Sign the contract with a blue ballpoint pen."),
    ("Radiergummi", "der", "die Radiergummis", "A1", "Lernen", "Mit dem Radiergummi lösche ich den Schreibfehler.", "ластик / стёрка", "Ластиком я стираю описку.", "eraser", "With the eraser I erase the typo."),
    ("Lineal", "das", "die Lineale", "A1", "Lernen", "Zieh eine gerade Linie mit dem Lineal.", "линейка", "Проведи прямую линию с помощью линейки.", "ruler", "Draw a straight line with the ruler."),
    ("Schere", "die", "die Scheren", "A1", "Lernen", "Die Kinder schneiden Papier mit einer Schere.", "ножницы", "Дети режут бумагу ножницами.", "scissors", "The children cut paper with scissors."),
    ("Tafel", "die", "die Tafeln", "A1", "Lernen", "Der Lehrer schreibt die Aufgabe an die Tafel.", "школьная доска", "Учитель пишет задание на доске.", "blackboard / board", "The teacher writes the task on the board."),
    ("Kreide", "die", "die Kreiden", "A1", "Lernen", "Auf der schwarzen Tafel sieht man weiße Kreide gut.", "мел", "На черной доске хорошо виден белый мел.", "chalk", "On the blackboard you can see white chalk well."),
    ("Schultasche", "die", "die Schultaschen", "A1", "Lernen", "Die Schultasche ist heute ziemlich schwer.", "школьный ранец / портфель", "Школьный ранец сегодня довольно тяжелый.", "school bag", "The school bag is quite heavy today."),
    ("Fach", "das", "die Fächer", "A1", "Lernen", "Mein liebstes Fach in der Schule war Biologie.", "школьный предмет", "Моим любимым предметом в школе была биология.", "subject", "My favorite subject in school was biology."),
    ("Unterricht", "der", "die Unterrichte", "A1", "Lernen", "Der deutsche Unterricht beginnt morgens um neun.", "урок / занятия", "Урок немецкого начинается в девять утра.", "lesson / classes", "German class begins at nine in the morning."),
    ("Stunde", "die", "die Stunden", "A1", "Lernen", "Eine Schulstunde dauert in Deutschland fünfundvierzig Minuten.", "урок / час", "Школьный урок в Германии длится сорок пять минут.", "lesson / hour", "A school lesson lasts forty-five minutes in Germany."),
    ("Pause", "die", "die Pausen", "A1", "Lernen", "In der großen Pause essen wir unseren Apfel.", "перемена / перерыв", "На большой перемене мы едим наше яблоко.", "break / recess", "During the long break we eat our apple."),
    ("Hausaufgabe", "die", "die Hausaufgaben", "A1", "Lernen", "Hast du deine Hausaufgaben schon fertig gemacht?", "домашнее задание", "Ты уже сделал домашние задания?", "homework", "Have you finished your homework already?"),
    ("Prüfung", "die", "die Prüfungen", "A2", "Lernen", "Für die B1-Prüfung muss man fleißig üben.", "экзамен", "К экзамену B1 нужно усердно готовиться.", "exam", "For the B1 exam you have to practice hard."),
    ("Test", "der", "die Tests", "A1", "Lernen", "Morgen schreiben wir einen kurzen Grammatiktest.", "тест / контрольная", "Завтра мы пишем короткий тест по грамматике.", "test", "Tomorrow we are writing a short grammar test."),
    ("Klausur", "die", "die Klausuren", "A2", "Lernen", "Die Studenten bereiten sich auf die schwere Klausur vor.", "письменный экзамен", "Студенты готовятся к сложному письменному экзамену.", "written exam", "The students prepare for the difficult written exam."),
    ("Note", "die", "die Noten", "A1", "Lernen", "Eine Eins ist die beste Note in der deutschen Schule.", "оценка / отметка", "Единица - лучшая оценка в немецкой школе.", "grade / mark", "A one is the best grade in German schools."),
    ("Zeugnis", "das", "die Zeugnisse", "A2", "Lernen", "Am Ende des Schuljahres gibt es das Zeugnis.", "аттестат / табель с оценками", "В конце учебного года выдают табель успеваемости.", "report card / certificate", "At the end of the school year there is the report card."),
    ("Diplom", "das", "die Diplome", "A2", "Lernen", "Sie erhielt stolz ihr Diplom an der Universität.", "диплом", "Она с гордостью получила свой диплом в университете.", "diploma", "She proudly received her diploma at the university."),
    ("Bibliothek", "die", "die Bibliotheken", "A1", "Lernen", "In der Bibliothek muss man ganz leise sein.", "библиотека", "В библиотеке нужно соблюдать полную тишину.", "library", "In the library one must be completely quiet."),
    ("Regal", "das", "die Regale", "A1", "Lernen", "Die schweren Lexika stehen im oberen Regal.", "полка / стеллаж", "Тяжелые словари стоят на верхней полке.", "shelf", "The heavy encyclopedias are on the upper shelf."),
    ("Seite", "die", "die Seiten", "A1", "Lernen", "Bitte schlagen Sie Seite fünfundfünfzig auf.", "страница", "Пожалуйста, откройте страницу пятьдесят пять.", "page", "Please turn to page fifty-five."),
    ("Kapitel", "das", "die Kapitel", "A2", "Lernen", "Das dritte Kapitel erklärt die Verben mit Akkusativ.", "глава", "Третья глава объясняет глаголы с винительным падежом.", "chapter", "The third chapter explains verbs with accusative."),
    ("Thema", "das", "die Themen", "A1", "Lernen", "Das heutige Thema unserer Stunde ist Einkaufen.", "тема", "Сегодняшняя тема нашего урока - покупки.", "topic / theme", "Today's topic of our lesson is shopping."),
    ("Text", "der", "die Texte", "A1", "Lernen", "Lies diesen kurzen Text laut vor.", "текст", "Прочитай этот короткий текст вслух.", "text", "Read this short text out loud."),
    ("Grammatik", "die", "die Grammatiken", "A1", "Lernen", "Deutsche Grammatik hat klare feste Regeln.", "грамматика", "Немецкая грамматика имеет четкие твердые правила.", "grammar", "German grammar has clear fixed rules."),
    ("Vokabel", "die", "die Vokabeln", "A1", "Lernen", "Jeden Tag lerne ich zehn neue Vokabeln mit Stork.", "слово (иностранное)", "Каждый день я учу десять новых слов с Аистом.", "vocabulary word", "Every day I learn ten new vocabulary words with Stork."),
    ("Wortschatz", "der", "die Wortschätze", "A2", "Lernen", "Ein reicher Wortschatz hilft beim freien Sprechen.", "словарный запас", "Богатый словарный запас помогает свободно говорить.", "vocabulary", "A rich vocabulary helps with speaking fluently."),
    ("Wörterbuch", "das", "die Wörterbücher", "A1", "Lernen", "Im Wörterbuch schlage ich die Bedeutung nach.", "словарь", "В словаре я смотрю значение слова.", "dictionary", "In the dictionary I look up the meaning."),
    ("Aussprache", "die", "die Aussprachen", "A2", "Lernen", "Seine Aussprache auf Deutsch ist sehr klar.", "произношение", "Его произношение на немецком очень четкое.", "pronunciation", "His pronunciation in German is very clear."),
    ("Regel", "die", "die Regeln", "A1", "Lernen", "Jedes Spiel und jede Sprache hat feste Regeln.", "правило", "У каждой игры и каждого языка есть твердые правила.", "rule", "Every game and every language has fixed rules."),
    ("Fehler", "der", "die Fehler", "A1", "Lernen", "Aus Fehlern lernt man am schnellsten.", "ошибка", "На ошибках учатся быстрее всего.", "mistake / error", "You learn fastest from mistakes."),
    ("Lösung", "die", "die Lösungen", "A1", "Lernen", "Die richtige Lösung steht am Ende des Buches.", "решение / ответ", "Правильный ответ находится в конце книги.", "solution / answer", "The correct solution is at the end of the book."),
    ("Antwort", "die", "die Antworten", "A1", "Lernen", "Ich kenne die Antwort auf deine Frage.", "ответ", "Я знаю ответ на твой вопрос.", "answer", "I know the answer to your question."),
    ("Frage", "die", "die Fragen", "A1", "Lernen", "Haben Sie noch eine wichtige Frage zum Text?", "вопрос", "У вас есть еще важный вопрос по тексту?", "question", "Do you have another important question about the text?"),
    ("Beispiel", "das", "die Beispiele", "A1", "Lernen", "Können Sie mir bitte ein anschauliches Beispiel nennen?", "пример", "Не могли бы вы привести мне наглядный пример?", "example", "Could you please give me a clear example?"),
    ("Referat", "das", "die Referate", "A2", "Lernen", "Morgen halte ich ein Referat über Goethe.", "доклад / реферат", "Завтра я выступаю с докладом о Гёте.", "presentation / report", "Tomorrow I give a presentation about Goethe."),
    ("Wissen", "das", "die Wissen", "A2", "Lernen", "Wissen ist die stärkste Kraft im Leben.", "знания", "Знания - самая сильная сила в жизни.", "knowledge", "Knowledge is the strongest power in life."),
    ("Bildung", "die", "die Bildungen", "B1", "Lernen", "Gute Bildung öffnet viele Türen im Beruf.", "образование", "Хорошее образование открывает многие двери в карьере.", "education", "Good education opens many doors in career."),

    # --- ZEIT & KALENDER (Время и календарь) ---
    ("Sekunde", "die", "die Sekunden", "A1", "Zeit", "Warte bitte eine kurze Sekunde auf mich.", "секунда", "Подожди меня, пожалуйста, одну короткую секунду.", "second", "Please wait a short second for me."),
    ("Minute", "die", "die Minuten", "A1", "Zeit", "Der Bus kommt in genau fünf Minuten.", "минута", "Автобус придет ровно через пять минут.", "minute", "The bus arrives in exactly five minutes."),
    ("Stunde", "die", "die Stunden", "A1", "Zeit", "Die Zugfahrt nach München dauert drei Stunden.", "час", "Поездка на поезде в Мюнхен длится три часа.", "hour", "The train ride to Munich takes three hours."),
    ("Morgen", "der", "die Morgen", "A1", "Zeit", "Guten Morgen! Hast du gut geschlafen?", "утро", "Доброе утро! Ты хорошо спал?", "morning", "Good morning! Did you sleep well?"),
    ("Vormittag", "der", "die Vormittage", "A1", "Zeit", "Am Vormittag arbeite ich meist am Computer.", "первая половина дня", "В первой половине дня я обычно работаю за компьютером.", "late morning", "In the late morning I mostly work on the computer."),
    ("Mittag", "der", "die Mittage", "A1", "Zeit", "Um zwölf Uhr mittags essen wir gemeinsam.", "полдень", "В двенадцать часов дня мы обедаем вместе.", "noon / midday", "At twelve noon we eat together."),
    ("Nachmittag", "der", "die Nachmittage", "A1", "Zeit", "Am Nachmittag trinken wir Kaffee und essen Kuchen.", "время после полудня", "После полудня мы пьем кофе и едим пирог.", "afternoon", "In the afternoon we drink coffee and eat cake."),
    ("Abend", "der", "die Abende", "A1", "Zeit", "Guten Abend! Wie war dein Tag heute?", "вечер", "Добрый вечер! Как прошел твой день сегодня?", "evening", "Good evening! How was your day today?"),
    ("Nacht", "die", "die Nächte", "A1", "Zeit", "Gute Nacht und schlaf schön!", "ночь", "Доброй ночи и приятных снов!", "night", "Good night and sleep tight!"),
    ("Mitternacht", "die", "die Mitternächte", "A2", "Zeit", "Um Mitternacht beginnt das neue Jahr mit Feuerwerk.", "полночь", "В полночь начинается новый год с фейерверками.", "midnight", "At midnight the new year begins with fireworks."),
    ("Woche", "die", "die Wochen", "A1", "Zeit", "Eine Woche hat sieben Tage.", "неделя", "В неделе семь дней.", "week", "A week has seven days."),
    ("Wochentag", "der", "die Wochentage", "A1", "Zeit", "Montag ist der erste Wochentag.", "будний день / день недели", "Понедельник - первый день недели.", "weekday", "Monday is the first day of the week."),
    ("Montag", "der", "die Montage", "A1", "Zeit", "Am Montag beginnt wieder die Arbeit.", "понедельник", "В понедельник снова начинается работа.", "Monday", "On Monday work begins again."),
    ("Dienstag", "der", "die Dienstage", "A1", "Zeit", "Am Dienstag gehe ich zum Deutschkurs.", "вторник", "Во вторник я иду на курс немецкого.", "Tuesday", "On Tuesday I go to German class."),
    ("Mittwoch", "der", "die Mittwoche", "A1", "Zeit", "Mittwoch ist die Mitte der Arbeitswoche.", "среда", "Среда - середина рабочей недели.", "Wednesday", "Wednesday is the middle of the work week."),
    ("Donnerstag", "der", "die Donnerstage", "A1", "Zeit", "Am Donnerstag treffen wir uns mit Freunden.", "четверг", "В четверг мы встречаемся с друзьями.", "Thursday", "On Thursday we meet with friends."),
    ("Freitag", "der", "die Freitage", "A1", "Zeit", "Am Freitag freuen sich alle aufs Wochenende.", "пятница", "В пятницу все радуются приближению выходных.", "Friday", "On Friday everyone looks forward to the weekend."),
    ("Samstag", "der", "die Samstage", "A1", "Zeit", "Am Samstag schlafe ich gerne lange aus.", "суббота", "В субботу я люблю подольше поспать.", "Saturday", "On Saturday I like sleeping in."),
    ("Sonntag", "der", "die Sonntage", "A1", "Zeit", "Am Sonntag haben die Geschäfte in Deutschland geschlossen.", "воскресенье", "В воскресенье магазины в Германии закрыты.", "Sunday", "On Sunday shops in Germany are closed."),
    ("Wochenende", "das", "die Wochenenden", "A1", "Zeit", "Ich wünsche dir ein schönes erholsames Wochenende!", "выходные", "Желаю тебе приятных и спокойных выходных!", "weekend", "I wish you a nice relaxing weekend!"),
    ("Monat", "der", "die Monate", "A1", "Zeit", "Das Jahr hat zwölf Monate.", "месяц", "В году двенадцать месяцев.", "month", "The year has twelve months."),
    ("Januar", "der", "die Januare", "A1", "Zeit", "Der Januar ist meistens der kälteste Monat.", "январь", "Январь обычно самый холодный месяц.", "January", "January is usually the coldest month."),
    ("Februar", "der", "die Februare", "A1", "Zeit", "Der Februar hat nur achtundzwanzig oder neunundzwanzig Tage.", "февраль", "В феврале всего двадцать восемь или двадцать девять дней.", "February", "February has only twenty-eight or twenty-nine days."),
    ("März", "der", "die Märze", "A1", "Zeit", "Im März beginnt der bunte Frühling.", "март", "В марте начинается цветущая весна.", "March", "In March colorful spring begins."),
    ("April", "der", "die Aprile", "A1", "Zeit", "Der April macht wettertechnisch, was er will.", "апрель", "Апрель в плане погоды делает все, что хочет.", "April", "April does what it wants weather-wise."),
    ("Mai", "der", "die Maie", "A1", "Zeit", "Im Mai blühen überall die Blumen.", "май", "В мае везде цветут цветы.", "May", "In May flowers bloom everywhere."),
    ("Juni", "der", "die Junis", "A1", "Zeit", "Der Juni bringt warme sonnige Tage.", "июнь", "Июнь приносит теплые солнечные дни.", "June", "June brings warm sunny days."),
    ("Juli", "der", "die Julis", "A1", "Zeit", "Im Juli beginnen in vielen Bundesländern die Ferien.", "июль", "В июле во многих землях начинаются каникулы.", "July", "In July holidays begin in many federal states."),
    ("August", "der", "die Auguste", "A1", "Zeit", "Der August ist perfekt für Urlaub am Meer.", "август", "Август идеален для отпуска на море.", "August", "August is perfect for a vacation by the sea."),
    ("September", "der", "die September", "A1", "Zeit", "Im September beginnt das neue Schuljahr.", "сентябрь", "В сентябре начинается новый учебный год.", "September", "In September the new school year begins."),
    ("Oktober", "der", "die Oktober", "A1", "Zeit", "Im Oktober färben sich die Blätter goldgelb.", "октябрь", "В октябре листья окрашиваются в золотисто-желтый цвет.", "October", "In October the leaves turn golden yellow."),
    ("November", "der", "die November", "A1", "Zeit", "Der November ist oft neblig und regnerisch.", "ноябрь", "Ноябрь часто туманный и дождливый.", "November", "November is often foggy and rainy."),
    ("Dezember", "der", "die Dezember", "A1", "Zeit", "Im Dezember feiern wir Weihnachten und Silvester.", "декабрь", "В декабре мы празднуем Рождество и Новый год.", "December", "In December we celebrate Christmas and New Year's Eve."),
    ("Jahreszeit", "die", "die Jahreszeiten", "A1", "Zeit", "Welche Jahreszeit magst du am liebsten?", "время года / сезон", "Какое время года ты любишь больше всего?", "season", "Which season do you like best?"),
    ("Frühling", "der", "die Frühlinge", "A1", "Zeit", "Im Frühling erwacht die Natur aus dem Winterschlaf.", "весна", "Весной природа просыпается от зимней спячки.", "spring", "In spring nature awakens from winter sleep."),
    ("Sommer", "der", "die Sommer", "A1", "Zeit", "Im Sommer essen wir gerne frisches Eis.", "лето", "Летом мы с удовольствием едим освежающее мороженое.", "summer", "In summer we enjoy eating fresh ice cream."),
    ("Herbst", "der", "die Herbste", "A1", "Zeit", "Im Herbst fallen die Blätter von den Bäumen.", "осень", "Осенью листья опадают с деревьев.", "autumn / fall", "In autumn the leaves fall from the trees."),
    ("Winter", "der", "die Winter", "A1", "Zeit", "Im kalten Winter bauen Kinder gerne Schneemänner.", "зима", "Холодной зимой дети с радостью лепят снеговиков.", "winter", "In cold winter children love building snowmen."),
    ("Jahrzehnt", "das", "die Jahrzehnte", "B1", "Zeit", "In diesem Jahrzehnt hat sich die Technik stark verändert.", "десятилетие", "В этом десятилетии технологии сильно изменились.", "decade", "In this decade technology has changed dramatically."),
    ("Jahrhundert", "das", "die Jahrhunderte", "B1", "Zeit", "Wir leben im einundzwanzigsten Jahrhundert.", "век / столетие", "Мы живем в двадцать первом веке.", "century", "We live in the twenty-first century."),
    ("Datum", "das", "die Daten", "A1", "Zeit", "Welches Datum haben wir heute?", "дата", "Какое сегодня число / дата?", "date", "What date is it today?"),
    ("Kalender", "der", "die Kalender", "A1", "Zeit", "Ich markiere deinen Geburtstag rot im Kalender.", "календарь", "Я отмечаю твой день рождения красным в календаре.", "calendar", "I mark your birthday in red on the calendar."),
    ("Uhrzeit", "die", "die Uhrzeiten", "A1", "Zeit", "Können Sie mir bitte die genaue Uhrzeit sagen?", "время на часах", "Не подскажете точное время?", "time of day", "Could you please tell me the exact time?"),
    ("Wecker", "der", "die Wecker", "A1", "Zeit", "Mein lauter Wecker klingelt jeden Morgen um sechs.", "будильник", "Мой громкий будильник звенит каждое утро в шесть.", "alarm clock", "My loud alarm clock rings every morning at six."),
    ("Zukunft", "die", "die Zukünfte", "A2", "Zeit", "Niemand weiß genau, was die Zukunft bringt.", "будущее", "Никто не знает точно, что принесет будущее.", "future", "No one knows exactly what the future brings."),
    ("Vergangenheit", "die", "die Vergangenheiten", "A2", "Zeit", "Die Vergangenheit kann man nicht mehr ändern.", "прошлое", "Прошлое уже нельзя изменить.", "past", "You cannot change the past anymore."),
    ("Gegenwart", "die", "die Gegenwarten", "A2", "Zeit", "Lebe im Hier und Jetzt in der Gegenwart.", "настоящее", "Живи здесь и сейчас в настоящем.", "present", "Live in the here and now in the present."),
    ("Moment", "der", "die Momente", "A1", "Zeit", "Einen kleinen Moment bitte, ich komme sofort.", "момент / минутка", "Один маленький момент, пожалуйста, я сейчас подойду.", "moment", "Just a moment please, I will be right there."),
    ("Dauer", "die", "die Dauern", "A2", "Zeit", "Die Dauer des Filmes beträgt zwei Stunden.", "продолжительность", "Продолжительность фильма составляет два часа.", "duration", "The duration of the movie is two hours."),
    ("Feiertag", "der", "die Feiertage", "A1", "Zeit", "Der erste Mai ist in Deutschland ein gesetzlicher Feiertag.", "праздничный (выходной) день", "Первое мая в Германии - официальный праздничный день.", "public holiday", "May 1st is a public holiday in Germany."),

    # --- NATUR & TIERE (Природа и животные) ---
    ("Baum", "der", "die Bäume", "A1", "Natur", "Vor unserem Haus wächst ein uralter Baum.", "дерево", "Перед нашим домом растет старое дерево.", "tree", "An ancient tree grows in front of our house."),
    ("Wald", "der", "die Wälder", "A1", "Natur", "Ein Spaziergang durch den Wald tut der Seele gut.", "лес", "Прогулка по лесу полезна для души.", "forest / woods", "A walk through the forest is good for the soul."),
    ("Blatt", "das", "die Blätter", "A1", "Natur", "Im Herbst wird jedes Blatt gelb oder rot.", "лист (растения)", "Осенью каждый лист становится желтым или красным.", "leaf", "In autumn every leaf turns yellow or red."),
    ("Ast", "der", "die Äste", "A2", "Natur", "Ein Vogel sitzt auf dem dicken Ast.", "ветка / сук", "Птица сидит на толстой ветке.", "branch", "A bird sits on the thick branch."),
    ("Blume", "die", "die Blumen", "A1", "Natur", "Er schenkte ihr einen Strauß bunter Blumen.", "цветок", "Он подарил ей букет разноцветных цветов.", "flower", "He gave her a bouquet of colorful flowers."),
    ("Rose", "die", "die Rosen", "A1", "Natur", "Die rote Rose duftet herrlich im Garten.", "роза", "Красная роза чудесно пахнет в саду.", "rose", "The red rose smells wonderful in the garden."),
    ("Tulpe", "die", "die Tulpen", "A1", "Natur", "Im Frühling blühen viele Tulpen in Holland.", "тюльпан", "Весной в Голландии цветет много тюльпанов.", "tulip", "In spring many tulips bloom in Holland."),
    ("Gras", "das", "die Gräser", "A1", "Natur", "Das grüne Gras ist noch nass vom Tau.", "трава", "Зеленая трава еще мокрая от росы.", "grass", "The green grass is still wet with dew."),
    ("Wiese", "die", "die Wiesen", "A1", "Natur", "Auf der Wiese grasen friedlich weiße Schafe.", "луг / поляна", "На лугу мирно пасутся белые овцы.", "meadow", "White sheep graze peacefully on the meadow."),
    ("Pflanze", "die", "die Pflanzen", "A1", "Natur", "Ich muss meine Zimmerpflanzen regelmäßig gießen.", "растение", "Я должен регулярно поливать свои комнатные растения.", "plant", "I must water my indoor plants regularly."),
    ("Garten", "der", "die Gärten", "A1", "Natur", "Im Garten wachsen Tomaten, Äpfel und Beeren.", "сад / огород", "В саду растут помидоры, яблоки и ягоды.", "garden", "In the garden grow tomatoes, apples, and berries."),
    ("Park", "der", "die Parks", "A1", "Natur", "Im Park joggen morgens viele Menschen.", "парк", "В парке по утрам бегают многие люди.", "park", "Many people jog in the park in the morning."),
    ("Stein", "der", "die Steine", "A1", "Natur", "Kinder werfen kleine Steine ins Wasser.", "камень", "Дети бросают маленькие камешки в воду.", "stone / rock", "Children throw small stones into the water."),
    ("Sand", "der", "die Sande", "A1", "Natur", "Der feine Sand am Strand ist herrlich warm.", "песок", "Мелкий песок на пляже приятно теплый.", "sand", "The fine sand on the beach is wonderfully warm."),
    ("Tal", "das", "die Täler", "A2", "Natur", "Ein schöner Fluss fließt durch das grüne Tal.", "долина", "Красивая река течет по зеленой долине.", "valley", "A beautiful river flows through the green valley."),
    ("Fluss", "der", "die Flüsse", "A1", "Natur", "Der Rhein ist ein sehr langer Fluss in Deutschland.", "река", "Рейн - очень длинная река в Германии.", "river", "The Rhine is a very long river in Germany."),
    ("Bach", "der", "die Bäche", "A2", "Natur", "Ein klarer Bach plätschert durch den Bergwald.", "ручей", "Прозрачный ручей журчит в горном лесу.", "brook / stream", "A clear stream ripples through the mountain forest."),
    ("Ozean", "der", "die Ozeane", "A2", "Natur", "Der Atlantische Ozean ist riesig und tief.", "океан", "Атлантический океан огромен и глубок.", "ocean", "The Atlantic Ocean is huge and deep."),
    ("Welle", "die", "die Wellen", "A2", "Natur", "Die hohen Wellen rollen an die Küste.", "волна", "Высокие волны накатывают на берег.", "wave", "The high waves roll onto the shore."),
    ("Küste", "die", "die Küsten", "A2", "Natur", "An der Ostseeküste weht oft ein frischer Wind.", "побережье", "На побережье Балтийского моря часто дует свежий ветер.", "coast / shore", "On the Baltic coast a fresh wind often blows."),
    ("Himmel", "der", "die Himmel", "A1", "Natur", "Am blauen Himmel scheint die warme Sonne.", "небо", "На синем небе светит теплое солнце.", "sky", "The warm sun shines in the blue sky."),
    ("Wolke", "die", "die Wolken", "A1", "Natur", "Dunkle Wolken kündigen baldigen Regen an.", "облако / туча", "Темные тучи предвещают скорый дождь.", "cloud", "Dark clouds announce coming rain."),
    ("Sonne", "die", "die Sonnen", "A1", "Natur", "Die Sonne wärmt die Erde im Frühling.", "солнце", "Солнце согревает землю весной.", "sun", "The sun warms the earth in spring."),
    ("Mond", "der", "die Monde", "A1", "Natur", "In der Nacht leuchtet der runde Mond hell.", "луна", "Ночью круглая луна ярко светит.", "moon", "At night the round moon shines brightly."),
    ("Stern", "der", "die Sterne", "A1", "Natur", "Am klaren Nachthimmel funkeln tausende Sterne.", "звезда", "На ясном ночном небе мерцают тысячи звезд.", "star", "In the clear night sky thousands of stars sparkle."),
    ("Wind", "der", "die Winde", "A1", "Natur", "Ein kalter Wind weht von den Bergen herab.", "ветер", "Холодный ветер дует с гор.", "wind", "A cold wind blows down from the mountains."),
    ("Sturm", "der", "die Stürme", "A2", "Natur", "Der starke Sturm brach viele Äste im Wald ab.", "шторм / буря", "Сильная буря сломала много веток в лесу.", "storm", "The strong storm broke many branches in the forest."),
    ("Regen", "der", "die Regen", "A1", "Natur", "Nach dem warmen Regen riecht die Natur herrlich.", "дождь", "После теплого дождя природа пахнет восхитительно.", "rain", "After the warm rain nature smells wonderful."),
    ("Schnee", "der", "die Schnee", "A1", "Natur", "Der weiße Schnee bedeckt die ganze Stadt.", "снег", "Белый снег укрывает весь город.", "snow", "The white snow covers the whole city."),
    ("Eis", "das", "die Eise", "A1", "Natur", "Auf dem See bildet sich im Winter dickes Eis.", "лед", "Зимой на озере образуется толстый лед.", "ice", "Thick ice forms on the lake in winter."),
    ("Nebel", "der", "die Nebel", "A2", "Natur", "Dichter Nebel macht das Fahren gefährlich.", "туман", "Густой туман делает вождение опасным.", "fog / mist", "Dense fog makes driving dangerous."),
    ("Gewitter", "das", "die Gewitter", "A2", "Natur", "Im Sommer gibt es nach heißer Luft oft ein Gewitter.", "гроза", "Летом после жары часто бывает гроза.", "thunderstorm", "In summer there is often a thunderstorm after hot air."),
    ("Blitz", "der", "die Blitze", "A2", "Natur", "Ein heller Blitz erleuchtete den Nachthimmel.", "молния", "Яркая молния озарила ночное небо.", "lightning", "A bright flash of lightning lit up the night sky."),
    ("Donner", "der", "die Donner", "A2", "Natur", "Kurz nach dem Blitz hörte man den lauten Donner.", "гром", "Вскоре после молнии послышался громкий гром.", "thunder", "Shortly after the lightning one heard the loud thunder."),
    ("Tier", "das", "die Tiere", "A1", "Natur", "Im Zoo kann man viele wilde Tiere sehen.", "животное", "В зоопарке можно увидеть много диких животных."),
    ("Vogel", "der", "die Vögel", "A1", "Natur", "Ein bunter Vogel singt frühmorgens auf dem Dach.", "птица", "Пестрая птица поет рано утром на крыше.", "bird", "A colorful bird sings early in the morning on the roof."),
    ("Hund", "der", "die Hunde", "A1", "Natur", "Der treue Hund wartet brav vor der Tür.", "собака", "Верная собака послушно ждет у двери.", "dog", "The loyal dog waits obediently at the door."),
    ("Katze", "die", "die Katzen", "A1", "Natur", "Die kleine Katze schläft friedlich auf dem Sofa.", "кошка", "Маленькая кошка мирно спит на диване.", "cat", "The little cat sleeps peacefully on the sofa."),
    ("Pferd", "das", "die Pferde", "A1", "Natur", "Sie reitet jedes Wochenende auf ihrem braunen Pferd.", "лошадь / конь", "Она каждые выходные катается на своей коричневой лошади.", "horse", "She rides her brown horse every weekend."),
    ("Kuh", "die", "die Kühe", "A1", "Natur", "Die Kuh gibt frische Milch auf dem Bauernhof.", "корова", "Корова дает свежее молоко на ферме.", "cow", "The cow gives fresh milk on the farm."),
    ("Schaf", "das", "die Schafe", "A1", "Natur", "Das Schaf liefert warme weiche Wolle.", "овца", "Овца дает теплую мягкую шерсть.", "sheep", "The sheep provides warm soft wool."),
    ("Schwein", "das", "die Schweine", "A1", "Natur", "Die Schweine suhlen sich gerne im Schlamm.", "свинья", "Свиньи с удовольствием валяются в грязи.", "pig", "Pigs enjoy wallowing in the mud."),
    ("Bär", "der", "die Bären", "A2", "Natur", "Der braune Bär schläft den ganzen Winter in der Höhle.", "медведь", "Бурый медведь спит всю зиму в берлоге.", "bear", "The brown bear sleeps in the cave all winter."),
    ("Wolf", "der", "die Wölfe", "A2", "Natur", "Im Wald heult nachts ein einsamer Wolf.", "волк", "В лесу ночью воет одинокий волк.", "wolf", "A lonely wolf howls in the forest at night."),
    ("Fuchs", "der", "die Füchse", "A2", "Natur", "Der schlaue rote Fuchs schleicht durchs Gebüsch.", "лиса", "Хитрый рыжий лис пробирается сквозь кусты.", "fox", "The clever red fox sneaks through the bushes."),
    ("Hase", "der", "die Hasen", "A1", "Natur", "Der kleine Hase hoppelt schnell über das Feld.", "заяц", "Маленький заяц быстро скачет по полю.", "hare / rabbit", "The little hare hops quickly across the field."),
    ("Biene", "die", "die Bienen", "A2", "Natur", "Die fleißige Biene sammelt Nektar von Blüten.", "пчела", "Трудолюбивая пчела собирает нектар с цветов.", "bee", "The industrious bee collects nectar from blossoms."),
    ("Schmetterling", "der", "die Schmetterlinge", "A2", "Natur", "Ein schöner bunter Schmetterling sitzt auf der Blume.", "бабочка", "Красивая разноцветная бабочка сидит на цветке.", "butterfly", "A beautiful colorful butterfly sits on the flower."),
    ("Spinne", "die", "die Spinnen", "A2", "Natur", "Die Spinne webt ein kunstvolles Netz in der Ecke.", "паук", "Паук плетет искусно паутину в углу.", "spider", "The spider weaves an elaborate web in the corner."),

    # --- ARBEIT & BERUF (Работа и офис) ---
    ("Beruf", "der", "die Berufe", "A1", "Arbeit", "Welchen Beruf möchten Sie in Zukunft ausüben?", "профессия", "Какую профессию вы хотите выбрать в будущем?", "profession / occupation", "What profession would you like to pursue in the future?"),
    ("Job", "der", "die Jobs", "A1", "Arbeit", "Er hat einen gut bezahlten Job in Frankfurt gefunden.", "работа / должность", "Он нашел хорошо оплачиваемую работу во Франкфурте.", "job", "He found a well-paid job in Frankfurt."),
    ("Arbeitsplatz", "der", "die Arbeitsplätze", "A2", "Arbeit", "Mein Arbeitsplatz ist modern und hell eingerichtet.", "рабочее место", "Мое рабочее место обустроено современно и светло.", "workplace", "My workplace is set up modern and bright."),
    ("Büro", "das", "die Büros", "A1", "Arbeit", "Unser Büro befindet sich im fünften Stockwerk.", "офис / кабинет", "Наш офис находится на пятом этаже.", "office", "Our office is on the fifth floor."),
    ("Firma", "die", "die Firmen", "A1", "Arbeit", "Die internationale Firma hat tausend Mitarbeiter.", "компания / фирма", "В международной фирме работает тысяча сотрудников.", "company / firm", "The international company has a thousand employees."),
    ("Unternehmen", "das", "die Unternehmen", "A2", "Arbeit", "Das junge Unternehmen wächst sehr erfolgreich.", "предприятие / бизнес", "Молодое предприятие растет очень успешно.", "enterprise / enterprise", "The young enterprise is growing very successfully."),
    ("Fabrik", "die", "die Fabriken", "A2", "Arbeit", "In der Fabrik werden moderne Autos gebaut.", "фабрика / завод", "На заводе производят современные автомобили.", "factory", "Modern cars are built in the factory."),
    ("Chef", "der", "die Chefs", "A1", "Arbeit", "Mein Chef ist sehr verständnisvoll und freundlich.", "начальник / шеф", "Мой начальник очень понимающий и дружелюбный.", "boss", "My boss is very understanding and friendly."),
    ("Kollege", "der", "die Kollegen", "A1", "Arbeit", "Ich verstehe mich gut mit meinen Kollegen im Team.", "коллега", "Я отлично лажу с коллегами по команде.", "colleague", "I get along well with my colleagues in the team."),
    ("Mitarbeiter", "der", "die Mitarbeiter", "A2", "Arbeit", "Die Firma sucht neue motivierte Mitarbeiter.", "сотрудник / работник", "Фирма ищет новых мотивированных сотрудников.", "employee / staff member", "The company is looking for new motivated employees."),
    ("Kunde", "der", "die Kunden", "A1", "Arbeit", "Der Kunde wünscht eine persönliche Beratung.", "клиент / покупатель", "Клиент желает получить личную консультацию.", "customer / client", "The customer requests personal advice."),
    ("Vertrag", "der", "die Verträge", "A2", "Arbeit", "Lesen Sie den Arbeitsvertrag vor der Unterschrift genau.", "договор / контракт", "Внимательно прочитайте трудовой договор перед подписью.", "contract", "Read the employment contract carefully before signing."),
    ("Gehalt", "das", "die Gehälter", "A2", "Arbeit", "Das Gehalt wird pünktlich zum Monatsende überwiesen.", "зарплата / оклад", "Зарплата перечисляется точно к концу месяца.", "salary", "The salary is transferred on time at the end of the month."),
    ("Lohn", "der", "die Löhne", "A2", "Arbeit", "Der Stundenlohn liegt über dem Mindestlohn.", "почасовая оплата / зарплата", "Почасовая ставка выше минимальной зарплаты.", "wage", "The hourly wage is above minimum wage."),
    ("Überstunde", "die", "die Überstunden", "B1", "Arbeit", "Diese Woche habe ich leider viele Überstunden gemacht.", "сверхурочный час", "На этой неделе я, к сожалению, много перерабатывал.", "overtime", "Unfortunately I worked a lot of overtime this week."),
    ("Feierabend", "der", "die Feierabende", "A1", "Arbeit", "Endlich Feierabend! Ich gehe jetzt nach Hause.", "окончание рабочего дня", "Наконец-то конец рабочего дня! Я иду домой.", "end of work / quitting time", "Finally quitting time! I am going home now."),
    ("Bewerbung", "die", "die Bewerbungen", "A2", "Arbeit", "Ich habe meine Bewerbung per E-Mail abgeschickt.", "резюме / заявка на работу", "Я отправил свое резюме по электронной почте.", "job application", "I sent my job application via email."),
    ("Lebenslauf", "der", "die Lebensläufe", "A2", "Arbeit", "Ein lückenloser Lebenslauf ist sehr wichtig.", "автобиография / резюме", "Резюме без пробелов очень важно.", "curriculum vitae / resume", "A gap-free CV is very important."),
    ("Vorstellungsgespräch", "das", "die Vorstellungsgespräche", "B1", "Arbeit", "Das Vorstellungsgespräch verlief äußerst positiv.", "собеседование при приеме на работу", "Собеседование прошло исключительно позитивно.", "job interview", "The job interview went extremely well."),
    ("Besprechung", "die", "die Besprechungen", "A2", "Arbeit", "Wir haben um zehn Uhr eine wichtige Besprechung.", "совещание / встреча", "У нас в десять часов важное совещание.", "meeting", "We have an important meeting at ten o'clock."),
    ("Präsentation", "die", "die Präsentationen", "A2", "Arbeit", "Seine Präsentation überzeugte alle Anwesenden.", "презентация", "Его презентация убедила всех присутствующих.", "presentation", "His presentation convinced everyone present."),
    ("Bericht", "der", "die Berichte", "A2", "Arbeit", "Schreiben Sie bitte einen kurzen Bericht über das Projekt.", "отчет / доклад", "Напишите, пожалуйста, краткий отчет о проекте.", "report", "Please write a short report about the project."),
    ("Dokument", "das", "die Dokumente", "A1", "Arbeit", "Speichern Sie das wichtige Dokument auf der Festplatte.", "документ", "Сохраните важный документ на жестком диске.", "document", "Save the important document on the hard drive."),
    ("Akte", "die", "die Akten", "B1", "Arbeit", "Die Akte liegt im Schrank mit den Unterlagen.", "дело / досье / папка с бумагами", "Папка с делом лежит в шкафу с документами.", "file / record", "The file is in the cabinet with the records."),
    ("Drucker", "der", "die Drucker", "A1", "Arbeit", "Der Drucker braucht neues Papier und Tinte.", "принтер", "Принтеру нужна новая бумага и чернила.", "printer", "The printer needs new paper and ink."),
    ("Laptop", "der", "die Laptops", "A1", "Arbeit", "Ich nehme meinen leichten Laptop mit auf Reisen.", "ноутбук", "Я беру свой легкий ноутбук в поездки.", "laptop", "I take my lightweight laptop on trips."),
    ("Tastatur", "die", "die Tastaturen", "A1", "Arbeit", "Die kabellose Tastatur tippt sich sehr angenehm.", "клавиатура", "На беспроводной клавиатуре очень приятно печатать.", "keyboard", "The wireless keyboard is very pleasant to type on."),
    ("Maus", "die", "die Mäuse", "A1", "Arbeit", "Die optische Maus reagiert sehr präzise.", "компьютерная мышь", "Оптическая мышь реагирует очень точно.", "mouse (computer)", "The optical mouse responds very precisely."),
    ("Bildschirm", "der", "die Bildschirme", "A1", "Arbeit", "Der große Bildschirm schont die Augen beim Arbeiten.", "монитор / экран", "Большой монитор бережет глаза при работе.", "screen / monitor", "The large monitor is easy on the eyes while working."),
    ("E-Mail", "die", "die E-Mails", "A1", "Arbeit", "Ich antworte sofort auf Ihre E-Mail.", "электронное письмо", "Я сейчас же отвечу на ваше электронное письмо.", "email", "I will reply to your email immediately."),
    ("Brief", "der", "die Briefe", "A1", "Arbeit", "Der Brief wird morgen mit der Post zugestellt.", "письмо (бумажное)", "Письмо будет доставлено завтра почтой.", "letter", "The letter will be delivered by mail tomorrow."),
    ("Karriere", "die", "die Karrieren", "B1", "Arbeit", "Mit Fleiß kann man eine steile Karriere machen.", "карьера", "Трудолюбием можно сделать стремительную карьеру.", "career", "With diligence you can build a steep career."),
    ("Erfolg", "der", "die Erfolge", "A2", "Arbeit", "Ich wünsche Ihnen viel Erfolg bei der neuen Arbeit!", "успех", "Желаю вам больших успехов на новой работе!", "success", "I wish you much success in your new job!"),
    ("Erfahrung", "die", "die Erfahrungen", "A2", "Arbeit", "Er bringt viele Jahre berufliche Erfahrung mit.", "опыт", "Он имеет многолетний профессиональный опыт.", "experience", "He brings many years of professional experience."),
    ("Projekt", "das", "die Projekte", "A2", "Arbeit", "Das internationale Projekt läuft noch bis Dezember.", "проект", "Международный проект длится до декабря.", "project", "The international project runs until December."),
    ("Aufgabe", "die", "die Aufgaben", "A1", "Arbeit", "Meine Hauptaufgabe ist die Betreuung der Kunden.", "задача / обязанность", "Моя главная задача - обслуживание клиентов.", "task / duty", "My main task is customer care."),
    ("Team", "das", "die Teams", "A1", "Arbeit", "In unserem jungen Team herrscht eine tolle Stimmung.", "команда / коллектив", "В нашем молодом коллективе царит отличная атмосфера.", "team", "There is a great atmosphere in our young team."),

    # --- MENSCHEN & FAMILIE (Люди и семья) ---
    ("Mensch", "der", "die Menschen", "A1", "Menschen", "Jeder Mensch hat das Recht auf freie Bildung.", "человек", "Каждый человек имеет право на бесплатное образование.", "human / person", "Every human being has the right to free education."),
    ("Person", "die", "die Personen", "A1", "Menschen", "Ein Tisch für vier Personen, bitte!", "персона / человек", "Столик на четыре персоны, пожалуйста!", "person", "A table for four persons, please!"),
    ("Mann", "der", "die Männer", "A1", "Menschen", "Der freundliche Mann hilft der alten Dame.", "мужчина", "Приветливый мужчина помогает пожилой даме.", "man", "The friendly man helps the elderly lady."),
    ("Frau", "die", "die Frauen", "A1", "Menschen", "Die junge Frau studiert Medizin in Heidelberg.", "женщина", "Молодая женщина изучает медицину в Гейдельберге.", "woman", "The young woman studies medicine in Heidelberg."),
    ("Kind", "das", "die Kinder", "A1", "Menschen", "Das Kind spielt fröhlich im Sandkasten.", "ребенок", "Ребенок весело играет в песочнице.", "child", "The child plays happily in the sandbox."),
    ("Baby", "das", "die Babys", "A1", "Menschen", "Das kleine Baby schläft ruhig im Kinderwagen.", "младенец / малыш", "Малыш спокойно спит в коляске.", "baby", "The little baby sleeps peacefully in the stroller."),
    ("Junge", "der", "die Jungen", "A1", "Menschen", "Der Junge fährt geschickt mit dem Skateboard.", "мальчик", "Мальчик ловко катается на скейтборде.", "boy", "The boy rides the skateboard skillfully."),
    ("Mädchen", "das", "die Mädchen", "A1", "Menschen", "Das kleine Mädchen liest gerne bunte Märchen.", "девочка", "Маленькая девочка любит читать красочные сказки.", "girl", "The little girl enjoys reading colorful fairy tales."),
    ("Familie", "die", "die Familien", "A1", "Menschen", "Meine Familie feiert Weihnachten immer zusammen.", "семья", "Моя семья всегда празднует Рождество вместе.", "family", "My family always celebrates Christmas together."),
    ("Eltern", "die", "die Eltern", "A1", "Menschen", "Meine Eltern wohnen in einem kleinen Haus am See.", "родители", "Мои родители живут в небольшом доме у озера.", "parents", "My parents live in a small house by the lake."),
    ("Vater", "der", "die Väter", "A1", "Menschen", "Mein Vater kocht sonntags die beste Lasagne.", "отец", "Мой отец готовит по воскресеньям лучшую лазанью.", "father", "My father cooks the best lasagna on Sundays."),
    ("Mutter", "die", "die Mütter", "A1", "Menschen", "Meine Mutter arbeitet als engagierte Lehrerin.", "мать", "Моя мать работает увлеченной учительницей.", "mother", "My mother works as a dedicated teacher."),
    ("Sohn", "der", "die Söhne", "A1", "Menschen", "Ihr ältester Sohn hat gerade das Abitur bestanden.", "сын", "Их старший сын только что сдал выпускные экзамены.", "son", "Her eldest son has just passed his high school diploma."),
    ("Tochter", "die", "die Töchter", "A1", "Menschen", "Unsere kleine Tochter lernt gerade sprechen.", "дочь", "Наша маленькая дочь как раз учится говорить.", "daughter", "Our little daughter is just learning to speak."),
    ("Bruder", "der", "die Brüder", "A1", "Menschen", "Mein jüngerer Bruder spielt gerne Basketball.", "брат", "Мой младший брат любит играть в баскетбол.", "brother", "My younger brother likes playing basketball."),
    ("Schwester", "die", "die Schwestern", "A1", "Menschen", "Meine ältere Schwester wohnt schon in Berlin.", "сестра", "Моя старшая сестра уже живет в Берлине.", "sister", "My older sister already lives in Berlin."),
    ("Geschwister", "die", "die Geschwister", "A1", "Menschen", "Hast du Geschwister oder bist du Einzelkind?", "братья и сестры", "У тебя есть братья или сестры, или ты один ребенок?", "siblings", "Do you have siblings or are you an only child?"),
    ("Großvater", "der", "die Großväter", "A1", "Menschen", "Mein Großvater erzählt spannende Geschichten aus der Jugend.", "дедушка", "Мой дедушка рассказывает захватывающие истории из юности.", "grandfather", "My grandfather tells exciting stories from his youth."),
    ("Großmutter", "die", "die Großmütter", "A1", "Menschen", "Meine Großmutter backt den süßesten Apfelkuchen.", "бабушка", "Моя бабушка печет самый сладкий яблочный пирог.", "grandmother", "My grandmother bakes the sweetest apple cake."),
    ("Enkel", "der", "die Enkel", "A2", "Menschen", "Die Großeltern freuen sich über jeden Besuch der Enkel.", "внук", "Бабушка с дедушкой радуются каждому визиту внуков.", "grandson / grandchild", "The grandparents are happy about every visit from the grandchildren."),
    ("Onkel", "der", "die Onkel", "A1", "Menschen", "Mein Onkel repariert Autos in seiner Werkstatt.", "дядя", "Мой дядя ремонтирует автомобили в своей мастерской.", "uncle", "My uncle repairs cars in his workshop."),
    ("Tante", "die", "die Tanten", "A1", "Menschen", "Tante Monika bringt immer Schokolade mit.", "тетя", "Тетя Моника всегда приносит с собой шоколад.", "aunt", "Aunt Monika always brings chocolate with her."),
    ("Cousin", "der", "die Cousins", "A2", "Menschen", "Mein Cousin und ich sind gleich alt.", "двоюродный брат (кузен)", "Мы с двоюродным братом ровесники.", "cousin (male)", "My cousin and I are the same age."),
    ("Cousine", "die", "die Cousinen", "A2", "Menschen", "Meine Cousine studiert Kunst in Wien.", "двоюродная сестра (кузина)", "Моя кузина изучает искусство в Вене.", "cousin (female)", "My cousin studies art in Vienna."),
    ("Freund", "der", "die Freunde", "A1", "Menschen", "Ein echter Freund hilft in jeder schweren Lage.", "друг", "Настоящий друг помогает в любой трудной ситуации.", "friend", "A true friend helps in any difficult situation."),
    ("Freundin", "die", "die Freundinnen", "A1", "Menschen", "Meine beste Freundin kennt mich seit der Schulzeit.", "подруга", "Моя лучшая подруга знает меня со школьных лет.", "friend (female) / girlfriend", "My best friend has known me since school days."),
    ("Nachbar", "der", "die Nachbarn", "A1", "Menschen", "Unser Nachbar gießt im Urlaub unsere Blumen.", "сосед", "Наш сосед поливает цветы во время нашего отпуска.", "neighbor", "Our neighbor waters our flowers while we are on vacation."),
    ("Nachbarin", "die", "die Nachbarinnen", "A1", "Menschen", "Die freundliche Nachbarin backt leckere Kekse.", "соседка", "Приветливая соседка печет вкусное печенье.", "neighbor (female)", "The friendly neighbor bakes delicious cookies."),
    ("Partner", "der", "die Partner", "A2", "Menschen", "Er und sein Partner haben zusammen eine Firma.", "партнер", "Он и его партнер вместе открыли фирму.", "partner", "He and his partner have a company together."),
    ("Ehemann", "der", "die Ehemänner", "A2", "Menschen", "Ihr Ehemann schenkt ihr zum Jahrestag Blumen.", "муж (супруг)", "Ее муж дарит ей цветы на годовщину.", "husband", "Her husband gives her flowers for their anniversary."),
    ("Ehefrau", "die", "die Ehefrauen", "A2", "Menschen", "Seine Ehefrau ist eine bekannte Architektin.", "жена (супруга)", "Его жена - известный архитектор.", "wife", "His wife is a well-known architect."),
    ("Hochzeit", "die", "die Hochzeiten", "A2", "Menschen", "Die Hochzeit fand in einer alten Burg statt.", "свадьба", "Свадьба состоялась в старинном замке.", "wedding", "The wedding took place in an ancient castle."),
    ("Alter", "das", "die Alter", "A1", "Menschen", "In welchem Alter hast du Deutsch gelernt?", "возраст", "В каком возрасте ты учил немецкий?", "age", "At what age did you learn German?"),
    ("Adresse", "die", "die Adressen", "A1", "Menschen", "Schreib bitte deine neue Adresse auf diesen Zettel.", "адрес", "Напиши, пожалуйста, свой новый адрес на этом листке.", "address", "Please write your new address on this slip of paper."),

    # --- STADT & GEBÄUDE (Город и здания) ---
    ("Zentrum", "das", "die Zentren", "A1", "Stadt", "Das historische Zentrum ist für Autos gesperrt.", "центр", "Исторический центр закрыт для автомобилей.", "center / downtown", "The historic center is closed to cars."),
    ("Vorort", "der", "die Vororte", "A2", "Stadt", "Sie wohnen ruhig in einem grünen Vorort.", "пригород", "Они живут спокойно в зеленом пригороде.", "suburb", "They live quietly in a green suburb."),
    ("Gasse", "die", "die Gassen", "A2", "Stadt", "In der schmalen Gasse gibt es kleine Boutiquen.", "переулок", "В узком переулке находятся маленькие бутики.", "alley / lane", "In the narrow alley there are small boutiques."),
    ("Platz", "der", "die Plätze", "A1", "Stadt", "Der zentrale Marktplatz ist voller Menschen.", "площадь", "Центральная рыночная площадь полна людей.", "square / plaza", "The central market square is full of people."),
    ("Kreuzung", "die", "die Kreuzungen", "A1", "Stadt", "Biegen Sie an der nächsten Kreuzung links ab.", "перекресток", "Поверните на следующем перекрестке налево.", "intersection / crossroads", "Turn left at the next intersection."),
    ("Bürgersteig", "der", "die Bürgersteige", "A2", "Stadt", "Fußgänger gehen sicher auf dem Bürgersteig.", "тротуар", "Пешеходы безопасно идут по тротуару.", "sidewalk / pavement", "Pedestrians walk safely on the sidewalk."),
    ("Ampel", "die", "die Ampeln", "A1", "Stadt", "Bei Rot an der Ampel muss man stehen bleiben.", "светофор", "На красный свет светофора нужно останавливаться.", "traffic light", "At a red traffic light one must stop."),
    ("Schild", "das", "die Schilder", "A1", "Stadt", "Das Schild zeigt die Richtung nach München an.", "дорожный знак / вывеска", "Знак показывает направление на Мюнхен.", "sign / road sign", "The sign indicates the direction to Munich."),
    ("Laterne", "die", "die Laternen", "A2", "Stadt", "Nachts leuchten die Laternen die Straße aus.", "фонарь (уличный)", "Ночью фонари освещают улицу.", "street lamp / lantern", "At night street lamps illuminate the street."),
    ("Gebäude", "das", "die Gebäude", "A1", "Stadt", "Das moderne Gebäude aus Glas spiegelt die Sonne.", "здание / постройка", "Современное здание из стекла отражает солнце.", "building", "The modern glass building reflects the sun."),
    ("Hochhaus", "das", "die Hochhäuser", "A2", "Stadt", "In Frankfurt stehen viele hohe Hochhäuser.", "высотный дом / высотка", "Во Франкфурте стоит много высоких высоток.", "high-rise / skyscraper", "In Frankfurt there are many tall high-rises."),
    ("Turm", "der", "die Türme", "A1", "Stadt", "Der alte Turm ragt hoch in den Himmel.", "башня", "Старая башня возвышается высоко в небо.", "tower", "The old tower rises high into the sky."),
    ("Kirche", "die", "die Kirchen", "A1", "Stadt", "Die Glocken der alten Kirche läuten laut.", "церковь", "Колокола старой церкви громко звонят.", "church", "The bells of the old church ring loudly."),
    ("Dom", "der", "die Dome", "A2", "Stadt", "Der gotische Dom ist das Wahrzeichen der Stadt.", "собор", "Готический собор - символ города.", "cathedral", "The Gothic cathedral is the landmark of the city."),
    ("Schloss", "das", "die Schlösser", "A1", "Stadt", "Das Schloss Neuschwanstein sieht aus wie im Märchen.", "замок / дворец", "Замок Нойшванштайн выглядит как в сказке.", "castle / palace", "Neuschwanstein Castle looks like in a fairy tale."),
    ("Rathaus", "das", "die Rathäuser", "A1", "Stadt", "Der Bürgermeister arbeitet im Rathaus.", "ратуша (мэрия)", "Мэр работает в ратуше.", "town hall", "The mayor works in the town hall."),
    ("Post", "die", "die Posten", "A1", "Stadt", "Ich bringe das schwere Paket zur Post.", "почта", "Я отношу тяжелую посылку на почту.", "post office / mail", "I take the heavy parcel to the post office."),
    ("Bank", "die", "die Banken", "A1", "Stadt", "Geld wechsle ich am besten in der Bank.", "банк (финансовый)", "Деньги я лучше всего меняю в банке.", "bank", "I change money best at the bank."),
    ("Geldautomat", "der", "die Geldautomaten", "A1", "Stadt", "Am Geldautomaten hebe ich Bargeld ab.", "банкомат", "В банкомате я снимаю наличные деньги.", "ATM / cash machine", "At the ATM I withdraw cash."),
    ("Polizei", "die", "die Polizeien", "A1", "Stadt", "Im Notfall ruft man die Polizei unter der 110.", "полиция", "В экстренном случае звонят в полицию по номеру 110.", "police", "In an emergency you call the police at 110."),
    ("Feuerwehr", "die", "die Feuerwehren", "A2", "Stadt", "Die Feuerwehr löscht den Brand schnell.", "пожарная служба", "Пожарные быстро тушат возгорание.", "fire department", "The fire department extinguishes the fire quickly."),
    ("Supermarkt", "der", "die Supermärkte", "A1", "Stadt", "Im Supermarkt kaufen wir frische Lebensmittel.", "супермаркет", "В супермаркете мы покупаем свежие продукты.", "supermarket", "In the supermarket we buy fresh groceries."),
    ("Markt", "der", "die Märkte", "A1", "Stadt", "Samstags kaufen wir Obst auf dem Wochenmarkt.", "рынок / базар", "По субботам мы покупаем фрукты на еженедельном рынке.", "market", "On Saturdays we buy fruit at the weekly market."),
    ("Spielplatz", "der", "die Spielplätze", "A1", "Stadt", "Die Kinder schaukeln auf dem Spielplatz.", "детская площадка", "Дети качаются на качелях на площадке.", "playground", "The children swing on the playground."),
    ("Brunnen", "der", "die Brunnen", "A2", "Stadt", "Das kühle Wasser plätschert im alten Brunnen.", "фонтан / колодец", "Прохладная вода журчит в старом фонтане.", "fountain / well", "Cool water trickles in the old fountain."),
    ("Brücke", "die", "die Brücken", "A1", "Stadt", "Die steinerne Brücke führt über den breiten Fluss.", "мост", "Каменный мост ведет через широкую реку.", "bridge", "The stone bridge leads over the wide river."),
    ("Tunnel", "der", "die Tunnel", "A2", "Stadt", "Der Zug fährt durch einen langen Tunnel im Berg.", "тоннель", "Поезд едет через длинный тоннель в горе.", "tunnel", "The train goes through a long tunnel in the mountain."),
    ("Parkplatz", "der", "die Parkplätze", "A1", "Stadt", "Vor dem Geschäft gibt es einen kostenlosen Parkplatz.", "парковка / парковочное место", "Перед магазином есть бесплатная парковка.", "parking lot", "In front of the shop there is a free parking lot."),
    ("Garage", "die", "die Garagen", "A1", "Stadt", "Mein Auto steht trocken in der Garage.", "гараж", "Моя машина стоит в сухости в гараже.", "garage", "My car stands dry in the garage."),

    # --- ZUHAUSE & MÖBEL (Дом и мебель) ---
    ("Wohnung", "die", "die Wohnungen", "A1", "Zuhause", "Wir suchen eine bezahlbare Drei-Zimmer-Wohnung.", "квартира", "Мы ищем доступную трехкомнатную квартиру.", "apartment / flat", "We are looking for an affordable three-room apartment."),
    ("Wohnzimmer", "das", "die Wohnzimmer", "A1", "Zuhause", "Abends schauen wir gemeinsam im Wohnzimmer fern.", "гостиная", "По вечерам мы вместе смотрим телевизор в гостиной.", "living room", "In the evening we watch TV together in the living room."),
    ("Schlafzimmer", "das", "die Schlafzimmer", "A1", "Zuhause", "Im Schlafzimmer steht ein großes Doppelbett.", "спальня", "В спальне стоит большая двуспальная кровать.", "bedroom", "In the bedroom stands a large double bed."),
    ("Küche", "die", "die Küchen", "A1", "Zuhause", "Die Küche ist der gemütlichste Raum der Wohnung.", "кухня", "Кухня - самая уютная комната в квартире.", "kitchen", "The kitchen is the coziest room in the apartment."),
    ("Badezimmer", "das", "die Badezimmer", "A1", "Zuhause", "Das Badezimmer hat sowohl eine Dusche als auch eine Wanne.", "ванная комната", "В ванной комнате есть как душ, так и ванна.", "bathroom", "The bathroom has both a shower and a tub."),
    ("Flur", "der", "die Flure", "A1", "Zuhause", "Im Flur hängt ein großer Spiegel an der Wand.", "коридор / прихожая", "В прихожей на стене висит большое зеркало.", "hallway / corridor", "In the hallway a large mirror hangs on the wall."),
    ("Balkon", "der", "die Balkone", "A1", "Zuhause", "Im Sommer frühstücken wir gern auf dem Balkon.", "балкон", "Летом мы любим завтракать на балконе.", "balcony", "In summer we enjoy having breakfast on the balcony."),
    ("Terrasse", "die", "die Terrassen", "A2", "Zuhause", "Auf der Terrasse grillen wir mit Freunden.", "терраса", "На террасе мы устраиваем барбекю с друзьями.", "terrace / patio", "On the terrace we barbecue with friends."),
    ("Keller", "der", "die Keller", "A1", "Zuhause", "Im kühlen Keller lagern wir Kartoffeln und Wein.", "подвал", "В прохладном подвале мы храним картофель и вино.", "basement / cellar", "In the cool cellar we store potatoes and wine."),
    ("Dachboden", "der", "die Dachböden", "A2", "Zuhause", "Auf dem Dachboden stehen alte Kisten mit Büchern.", "чердак", "На чердаке стоят старые коробки с книгами.", "attic", "In the attic there are old boxes with books."),
    ("Tür", "die", "die Türen", "A1", "Zuhause", "Schließe bitte die Haustür fest ab.", "дверь", "Запри, пожалуйста, входную дверь на ключ.", "door", "Please lock the front door securely."),
    ("Fenster", "das", "die Fenster", "A1", "Zuhause", "Öffne das Fenster, wir brauchen frische Luft.", "окно", "Открой окно, нам нужен свежий воздух.", "window", "Open the window, we need fresh air."),
    ("Wand", "die", "die Wände", "A1", "Zuhause", "An der weißen Wand hängt ein schönes Bild.", "стена", "На белой стене висит красивая картина.", "wall", "On the white wall hangs a nice picture."),
    ("Decke", "die", "die Decken", "A1", "Zuhause", "An der hohen Decke hängt eine moderne Lampe.", "потолок / одеяло", "К высокому потолку подвешена современная лампа.", "ceiling / blanket", "On the high ceiling hangs a modern lamp."),
    ("Boden", "der", "die Böden", "A1", "Zuhause", "Auf dem hölzernen Boden liegt ein warmer Teppich.", "пол", "На деревянном полу лежит теплый ковер.", "floor", "On the wooden floor lies a warm carpet."),
    ("Treppe", "die", "die Treppen", "A1", "Zuhause", "Ich nehme die Treppe statt des Aufzugs.", "лестница", "Я иду по лестнице вместо лифта.", "stairs / staircase", "I take the stairs instead of the elevator."),
    ("Aufzug", "der", "die Aufzüge", "A1", "Zuhause", "Der Aufzug fährt bis in die zehnte Etage.", "лифт", "Лифт едет до десятого этажа.", "elevator / lift", "The elevator goes up to the tenth floor."),
    ("Klingel", "die", "die Klingeln", "A2", "Zuhause", "Ich hörte die Klingel an der Wohnungstür.", "дверной звонок", "Я услышал звонок в дверь квартиры.", "doorbell", "I heard the doorbell at the apartment door."),
    ("Sofa", "das", "die Sofas", "A1", "Zuhause", "Das bequeme Sofa lädt zum Entspannen ein.", "диван", "Удобный диван так и манит отдохнуть.", "sofa / couch", "The comfortable sofa invites you to relax."),
    ("Sessel", "der", "die Sessel", "A1", "Zuhause", "Im weichen Sessel lese ich mein Buch.", "кресло", "В мягком кресле я читаю свою книгу.", "armchair", "In the soft armchair I read my book."),
    ("Tisch", "der", "die Tische", "A1", "Zuhause", "Wir sitzen alle zusammen am großen Tisch.", "стол", "Мы все вместе сидим за большим столом.", "table", "We all sit together at the big table."),
    ("Stuhl", "der", "die Stühle", "A1", "Zuhause", "Nimm dir einen bequemen Stuhl und setz dich.", "стул", "Возьми удобный стул и присаживайся.", "chair", "Take a comfortable chair and sit down."),
    ("Bett", "das", "die Betten", "A1", "Zuhause", "Nach einem langen Tag freue ich mich aufs Bett.", "кровать", "После долгого дня я с нетерпением жду кровати.", "bed", "After a long day I look forward to bed."),
    ("Kissen", "das", "die Kissen", "A1", "Zuhause", "Das Kissen ist herrlich weich und bequem.", "подушка", "Подушка восхитительно мягкая и удобная.", "pillow / cushion", "The pillow is wonderfully soft and comfortable."),
    ("Schrank", "der", "die Schränke", "A1", "Zuhause", "Meine Kleidung hängt ordentlich im Schrank.", "шкаф", "Моя одежда аккуратно висит в шкафу.", "closet / wardrobe", "My clothes hang neatly in the wardrobe."),
    ("Lampe", "die", "die Lampen", "A1", "Zuhause", "Mach bitte die Lampe an, es wird dunkel.", "лампа / светильник", "Включи, пожалуйста, лампу, становится темно.", "lamp", "Please turn on the lamp, it is getting dark."),
    ("Spiegel", "der", "die Spiegel", "A1", "Zuhause", "Sie blickt kurz in den Spiegel vor dem Hinausgehen.", "зеркало", "Она бросает быстрый взгляд в зеркало перед выходом.", "mirror", "She glances briefly into the mirror before leaving."),
    ("Teppich", "der", "die Teppiche", "A1", "Zuhause", "Der bunte Teppich wärmt den Fußboden.", "ковер", "Пестрый ковер согревает пол.", "carpet / rug", "The colorful carpet warms the floor."),
    ("Vorhang", "der", "die Vorhänge", "A2", "Zuhause", "Zieh die Vorhänge zu, damit die Sonne nicht blendet.", "штора / занавеска", "Задерни шторы, чтобы солнце не слепило.", "curtain", "Draw the curtains so the sun does not blind you."),
    ("Fernseher", "der", "die Fernseher", "A1", "Zuhause", "Wir schalten den Fernseher für die Nachrichten ein.", "телевизор", "Мы включаем телевизор ради новостей.", "television / TV", "We turn on the television for the news."),
    ("Kühlschrank", "der", "die Kühlschränke", "A1", "Zuhause", "Die Milch steht kühl im Kühlschrank.", "холодильник", "Молоко стоит в прохладе в холодильнике.", "refrigerator / fridge", "The milk is kept cold in the refrigerator."),
    ("Herd", "der", "die Herde", "A1", "Zuhause", "Die Suppe kocht auf dem heißen Herd.", "плита (кухонная)", "Суп варится на горячей плите.", "stove / cooker", "The soup cooks on the hot stove."),
    ("Backofen", "der", "die Backöfen", "A2", "Zuhause", "Der Kuchen backt eine Stunde im Backofen.", "духовка", "Пирог печется один час в духовке.", "oven", "The cake bakes for an hour in the oven."),
    ("Spülmaschine", "die", "die Spülmaschinen", "A2", "Zuhause", "Die Spülmaschine wäscht das schmutzige Geschirr.", "посудомоечная машина", "Посудомойка моет грязную посуду.", "dishwasher", "The dishwasher washes the dirty dishes."),
    ("Waschmaschine", "die", "die Waschmaschinen", "A1", "Zuhause", "Ich belade die Waschmaschine mit weißer Wäsche.", "стиральная машина", "Я загружаю стиральную машину белым бельем.", "washing machine", "I load the washing machine with white laundry."),
    ("Mikrowelle", "die", "die Mikrowellen", "A2", "Zuhause", "In der Mikrowelle wärme ich das Essen auf.", "микроволновка", "В микроволновке я разогреваю еду.", "microwave", "In the microwave I warm up the food."),
    ("Wasserkocher", "der", "die Wasserkocher", "A2", "Zuhause", "Mit dem Wasserkocher kocht das Wasser in zwei Minuten.", "электрический чайник", "С чайником вода закипает за две минуты.", "electric kettle", "With the electric kettle the water boils in two minutes."),
    ("Dusche", "die", "die Duschen", "A1", "Zuhause", "Eine kalte Dusche erfrischt am Morgen.", "душ", "Холодный душ освежает по утрам.", "shower", "A cold shower refreshes in the morning."),
    ("Badewanne", "die", "die Badewannen", "A1", "Zuhause", "Ein warmes Bad in der Wanne tut gut.", "ванна", "Теплая ванна полезна для отдыха.", "bathtub", "A warm bath in the tub is good."),
    ("Toilette", "die", "die Toiletten", "A1", "Zuhause", "Wo ist hier bitte die Toilette?", "туалет", "Где здесь, пожалуйста, туалет?", "toilet / restroom", "Where is the restroom here, please?"),
    ("Heizung", "die", "die Heizungen", "A1", "Zuhause", "Im kalten Winter drehen wir die Heizung auf.", "отопление / батарея", "Холодной зимой мы включаем отопление.", "heating / radiator", "In cold winter we turn up the heating."),
    ("Staubsauger", "der", "die Staubsauger", "A2", "Zuhause", "Mit dem Staubsauger reinige ich den Teppich.", "пылесос", "Пылесосом я чищу ковер.", "vacuum cleaner", "With the vacuum cleaner I clean the carpet.")
]

def build_full_dataset():
    p500 = DATA_DIR / "words_500.json"
    with open(p500, "r", encoding="utf-8") as f:
        master_list = json.load(f)

    existing_set = {item["word"] for item in master_list}
    print(f"Base words count: {len(existing_set)}")

    added = 0
    for item in NEW_EXPANDED_WORDS:
        word = item[0]
        if word not in existing_set:
            existing_set.add(word)
            master_list.append({
                "word": item[0],
                "article": item[1],
                "plural": item[2],
                "level": item[3],
                "category": item[4],
                "example_de": item[5],
                "translations": {
                    "ru": {"tr": item[6], "example_tr": item[7]},
                    "en": {"tr": item[8], "example_tr": item[9]}
                }
            })
            added += 1

    print(f"Added {added} new words. Total now: {len(master_list)}")
    return master_list

if __name__ == "__main__":
    full_data = build_full_dataset()
